In [2]:
USE_OPTUNA = True

# Main Orchestration

This notebook runs the ASM1 simulation model from the source package and persists the generated dataset and metadata under the repository data contract.

In [3]:
import pandas as pd
from src.models.simulation import run_asm1_simulation

simulation_result = run_asm1_simulation(save_artifacts=True)

dataset = simulation_result["dataset"]
metadata = simulation_result["metadata"]
artifact_paths = simulation_result["artifact_paths"]
petersen_matrix = simulation_result["petersen_matrix"]
composition_matrix = simulation_result["composition_matrix"]

print(f"Generated {len(dataset)} rows for {metadata['simulation_name']}.")
print(f"Dataset saved to: {artifact_paths['dataset_csv']}")
print(f"Metadata saved to: {artifact_paths['metadata_json']}")
print(f"Petersen matrix shape: {petersen_matrix.shape}")
print(f"Composition matrix shape: {composition_matrix.shape}")

display(dataset.head())
display(pd.Series(metadata, name="value").to_frame())
display(pd.DataFrame(petersen_matrix, index=metadata["processes"], columns=metadata["state_columns"]))
display(pd.DataFrame(composition_matrix, index=metadata["measured_output_columns"], columns=metadata["state_columns"]))

Generated 10000 rows for asm1_simulation.
Dataset saved to: C:\Users\eselerio\projects\pibre-model\data\asm1_simulation\data_20260328_074108.csv
Metadata saved to: C:\Users\eselerio\projects\pibre-model\data\asm1_simulation\metadata_20260328_074108.json
Petersen matrix shape: (7, 11)
Composition matrix shape: (15, 11)

,HRT,Aeration,In_S_S,In_S_I,In_S_NH4_N,In_S_NO3_N,In_S_PO4_P,In_S_O2,In_S_Alkalinity,In_X_I,...,Out_S_O2,Out_S_Alkalinity,Out_X_I,Out_X_S,Out_X_H,Out_X_AUT,Out_COD,Out_TSS,Out_TN,Out_TP
0,67.605899,1.965798,219.312089,50.721491,49.768123,2.092104,2.941773,0.487811,217.005146,98.606431,...,6.598106,6.519561,144.769201,0.036221,130.346255,6.611283e+00,336.126175,231.865851,48.080815,3.463250
1,58.703010,1.291958,228.097090,51.038994,26.407833,1.663754,2.638173,0.413816,193.699592,95.808774,...,6.312613,160.556189,147.237816,0.040578,168.266355,4.738239e+00,375.045968,266.162930,25.024892,4.196565
2,40.542296,1.340364,164.009781,23.066264,23.708711,2.049147,9.447622,0.483755,138.648564,57.045971,...,6.053080,111.707759,89.386339,0.062472,153.909402,1.761867e+00,273.069228,207.190751,22.171294,9.084680
3,23.994492,1.011043,200.566519,50.600634,48.809093,2.100795,5.123666,0.416130,224.857584,58.747838,...,3.382549,178.921173,82.656596,0.069198,192.139566,2.615893e+00,334.693278,237.324259,49.378327,5.351564
4,57.899931,1.952077,221.646388,66.539560,44.091119,2.342187,6.589158,0.284371,105.163460,31.453007,...,6.956201,109.299046,84.694963,0.048673,177.977664,1.000000e-08,333.244790,223.737624,39.549702,5.685756

                                                                      value
simulation_name                                             asm1_simulation
n_samples                                                             10000
random_seed                                                              42
dependent_columns         [Out_S_S, Out_S_I, Out_S_NH4_N, Out_S_NO3_N, O...
independent_columns       [HRT, Aeration, In_S_S, In_S_I, In_S_NH4_N, In...
identifier_columns                                                       []
ignored_columns                                                          []
dataset_file                  data/asm1_simulation/data_20260328_074108.csv
state_columns             [S_S, S_I, S_NH4_N, S_NO3_N, S_PO4_P, S_O2, S_...
measured_output_columns   [COD, TSS, TN, TP, S_S, S_I, S_NH4_N, S_NO3_N,...
operational_columns                                         [HRT, Aeration]
processes                 [Hydrolysis, Aerobic heterotrophic growth, Ano...
process_types             [biochemical, biochemical, biochemical, bioche...
petersen_matrix_shape                                               [7, 11]
composition_matrix_shape                                           [15, 11]
schema_version                                                          3.2

,S_S,S_I,S_NH4_N,S_NO3_N,S_PO4_P,S_O2,S_Alkalinity,X_I,X_S,X_H,X_AUT
Hydrolysis,1.000000,0.0,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,-1.0,0.0,0.0
Aerobic heterotrophic growth,-1.492537,0.0,-0.086000,0.000000,-0.0200,-0.492537,0.000000,0.0,0.0,1.0,0.0
Anoxic heterotrophic growth,-1.492537,0.0,-0.086000,-0.172216,-0.0200,0.000000,0.614811,0.0,0.0,1.0,0.0
Autotrophic growth and nitrification,0.000000,0.0,-4.252667,4.166667,-0.0200,-19.041667,-29.750000,0.0,0.0,0.0,1.0
Heterotrophic decay,0.000000,0.0,0.048000,0.000000,0.0134,0.000000,0.000000,0.2,0.8,-1.0,0.0
Autotrophic decay,0.000000,0.0,0.048000,0.000000,0.0134,0.000000,0.000000,0.2,0.8,0.0,-1.0
Aeration,0.000000,0.0,0.000000,0.000000,0.0000,1.000000,0.000000,0.0,0.0,0.0,0.0

,S_S,S_I,S_NH4_N,S_NO3_N,S_PO4_P,S_O2,S_Alkalinity,X_I,X_S,X_H,X_AUT
COD,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.000,1.000,1.000,1.000
TSS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.750,0.750,0.900,0.900
TN,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.030,0.040,0.086,0.086
TP,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.005,0.007,0.020,0.020
S_S,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000
S_I,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000
S_NH4_N,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000
S_NO3_N,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000,0.000,0.000,0.000
S_PO4_P,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.000,0.000,0.000,0.000
S_O2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.000,0.000,0.000,0.000
S_Alkalinity,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000,0.000,0.000,0.000
X_I,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000,0.000,0.000,0.000
X_S,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,1.000,0.000,0.000
X_H,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,1.000,0.000
X_AUT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,1.000

In [4]:
import numpy as np
from scipy.linalg import null_space

macroscopic_stoichiometric_matrix = petersen_matrix @ composition_matrix.T
constraint_basis = null_space(macroscopic_stoichiometric_matrix)
A_matrix = constraint_basis.T

A_matrix = np.round(A_matrix, 5)
A_matrix[np.abs(A_matrix) < 1e-10] = 0.0

for row_index in range(A_matrix.shape[0]):
    non_zero_entries = A_matrix[row_index, A_matrix[row_index, :] != 0]
    if len(non_zero_entries) > 0:
        A_matrix[row_index, :] = A_matrix[row_index, :] / non_zero_entries[0]

print(f"Macroscopic stoichiometric matrix shape: {macroscopic_stoichiometric_matrix.shape}")
print(f"A_matrix shape: {A_matrix.shape}")
display(
    pd.DataFrame(
        macroscopic_stoichiometric_matrix,
        index=metadata["processes"],
        columns=metadata["measured_output_columns"],
    )
)
display(
    pd.DataFrame(
        A_matrix,
        index=[f"constraint_{index + 1}" for index in range(A_matrix.shape[0])],
        columns=metadata["measured_output_columns"],
    )
)

Macroscopic stoichiometric matrix shape: (7, 15)
A_matrix shape: (8, 15)

,COD,TSS,TN,TP,S_S,S_I,S_NH4_N,S_NO3_N,S_PO4_P,S_O2,S_Alkalinity,X_I,X_S,X_H,X_AUT
Hydrolysis,0.000000,-0.75,-4.000000e-02,-0.007,1.000000,0.0,0.000000,0.000000,0.0000,0.000000,0.000000,0.0,-1.0,0.0,0.0
Aerobic heterotrophic growth,-0.492537,0.90,0.000000e+00,0.000,-1.492537,0.0,-0.086000,0.000000,-0.0200,-0.492537,0.000000,0.0,0.0,1.0,0.0
Anoxic heterotrophic growth,-0.492537,0.90,-1.722158e-01,0.000,-1.492537,0.0,-0.086000,-0.172216,-0.0200,0.000000,0.614811,0.0,0.0,1.0,0.0
Autotrophic growth and nitrification,1.000000,0.90,-3.053113e-16,0.000,0.000000,0.0,-4.252667,4.166667,-0.0200,-19.041667,-29.750000,0.0,0.0,0.0,1.0
Heterotrophic decay,0.000000,-0.15,0.000000e+00,0.000,0.000000,0.0,0.048000,0.000000,0.0134,0.000000,0.000000,0.2,0.8,-1.0,0.0
Autotrophic decay,0.000000,-0.15,0.000000e+00,0.000,0.000000,0.0,0.048000,0.000000,0.0134,0.000000,0.000000,0.2,0.8,0.0,-1.0
Aeration,0.000000,0.00,0.000000e+00,0.000,0.000000,0.0,0.000000,0.000000,0.0000,1.000000,0.000000,0.0,0.0,0.0,0.0

,COD,TSS,TN,TP,S_S,S_I,S_NH4_N,S_NO3_N,S_PO4_P,S_O2,S_Alkalinity,X_I,X_S,X_H,X_AUT
constraint_1,1.0,-0.341984,-6.720902,2.321222,-0.296067,0.515472,-4.175085,17.868836,0.003594,0.0,3.122779,-0.109802,0.213017,-0.000599,-0.000599
constraint_2,1.0,9.113924,-4.177215,2.227848,-10.050633,-3.734177,5.455696,-0.341772,1265.594937,0.0,-1.265823,3.000000,-16.734177,3.063291,3.063291
constraint_3,1.0,-0.337780,1.168354,-0.460427,-0.656913,0.551202,-2.090804,-0.122995,0.007337,0.0,0.292828,0.218439,-0.447058,-0.363563,-0.363563
constraint_4,1.0,0.886954,3.558060,33.256489,-0.106557,3.825478,-3.001366,-3.794399,-0.048839,0.0,-0.066257,2.357923,-1.146858,-0.723702,-0.723702
constraint_5,1.0,9.459529,2.873589,-1.610771,9.228958,-6.330861,-3.070622,0.987101,-0.051596,0.0,1.081587,27.154789,2.030635,5.488230,5.488230
constraint_6,1.0,-0.371289,-0.313871,0.015515,-0.665825,0.071801,0.746318,0.001148,-0.013268,0.0,-0.087595,0.527225,-0.374897,-0.103142,-0.103142
constraint_7,1.0,-67.680585,5.728601,7.211900,-15.098121,-41.360125,-13.583507,-2.923800,0.596033,0.0,0.786013,-0.500000,35.382046,37.713987,37.713987
constraint_8,1.0,1.952671,0.367449,0.744783,-0.694958,-8.665701,-0.714428,0.088867,-0.056715,-0.0,0.127808,-1.466301,-2.179331,-2.364653,-2.364653

In [5]:
import pandas as pd

from src.utils.process import (
    build_measured_supervised_dataset,
    make_train_test_split,
    sample_dataset_fraction,
)
from src.utils.simulation import load_ml_orchestration_params

ml_orchestration_params = load_ml_orchestration_params()
ml_orchestration = ml_orchestration_params["hyperparameters"]

measured_dataset = build_measured_supervised_dataset(
    dataset,
    metadata,
    composition_matrix,
)
main_dataset_splits = make_train_test_split(
    measured_dataset,
    test_fraction=float(ml_orchestration["test_fraction"]),
    random_seed=int(ml_orchestration["random_seed"]),
)
optuna_dataset = sample_dataset_fraction(
    main_dataset_splits.train,
    fraction=float(ml_orchestration["optuna_dataset_fraction"]),
    random_seed=int(ml_orchestration["random_seed"]),
)
tuning_dataset_splits = make_train_test_split(
    optuna_dataset,
    test_fraction=float(ml_orchestration["optuna_test_fraction"]),
    random_seed=int(ml_orchestration["random_seed"]),
)

split_sizes = {
    "train": len(main_dataset_splits.train.features),
    "test": len(main_dataset_splits.test.features),
    "optuna_dataset": len(optuna_dataset.features),
    "optuna_train": len(tuning_dataset_splits.train.features),
    "optuna_test": len(tuning_dataset_splits.test.features),
}

print("Notebook-managed ML orchestration is ready.")
print(f"Main split sizes: train={split_sizes['train']}, test={split_sizes['test']}")
print(
    "Optuna subset sizes: "
    f"dataset={split_sizes['optuna_dataset']}, train={split_sizes['optuna_train']}, test={split_sizes['optuna_test']}"
)

display(pd.DataFrame([ml_orchestration]))
display(pd.DataFrame([split_sizes]))

Notebook-managed ML orchestration is ready.
Main split sizes: train=8000, test=2000
Optuna subset sizes: dataset=800, train=640, test=160

,random_seed,test_fraction,optuna_dataset_fraction,optuna_test_fraction,tuning_epochs,n_trials,timeout_seconds
0,42,0.2,0.1,0.2,500,30,None

   train  test  optuna_dataset  optuna_train  optuna_test
0   8000  2000             800           640          160

In [6]:
import pandas as pd

from src.models.ml import load_uncobre_params, run_uncobre_pipeline
from src.utils.train import tune_uncobre_hyperparameters

uncobre_params = load_uncobre_params()

uncobre_hyperparameters = dict(uncobre_params["training_defaults"])
uncobre_optuna_summary = None
if USE_OPTUNA:
    uncobre_hyperparameters, uncobre_optuna_summary = tune_uncobre_hyperparameters(
        tuning_dataset_splits.train,
        tuning_dataset_splits.test,
        A_matrix=A_matrix,
        model_params=uncobre_params,
        n_trials=int(ml_orchestration["n_trials"]),
        timeout=ml_orchestration["timeout_seconds"],
    )

uncobre_result = run_uncobre_pipeline(
    main_dataset_splits.train,
    main_dataset_splits.test,
    A_matrix,
    model_params=uncobre_params,
    model_hyperparameters=uncobre_hyperparameters,
    optuna_summary=uncobre_optuna_summary,
    persist_artifacts=True,
)

print("UNCOBRE training complete.")
print(f"Measured-output targets: {', ' .join(metadata['measured_output_columns'])}")
print(f"Split sizes: {split_sizes}")
print(f"Saved model bundle: {uncobre_result['artifact_paths']['model_bundle']}")
print(f"Saved metrics summary: {uncobre_result['artifact_paths']['metrics']}")
print(f"Saved Optuna summary: {uncobre_result['artifact_paths']['optuna']}")

display(pd.DataFrame([uncobre_result["best_hyperparameters"]]))
display(pd.DataFrame([split_sizes]))
display(pd.Series(uncobre_result["artifact_paths"], name="path").to_frame())
display(uncobre_result["train_report"]["aggregate_metrics"])
display(uncobre_result["test_report"]["aggregate_metrics"])
display(uncobre_result["test_report"]["per_target_metrics"])
display(uncobre_result["test_report"]["constraint_residuals"].describe().T)

[I 2026-03-28 07:41:08,842] A new study created in memory with name: uncobre_study
uncobre_study [validation_projected_mse]:   0%|          | 0/30 [00:00<?, ?trial/s][I 2026-03-28 07:41:08,863] Trial 0 finished with value: 121.89379310210032 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 2.465832945854912, 'fit_intercept': True, 'include_bias': False}. Best is trial 0 with value: 121.89379310210032.
uncobre_study [validation_projected_mse]:   3%|▎         | 1/30 [00:00<00:00, 54.09trial/s, best=121.894, objective=121.894][I 2026-03-28 07:41:08,906] Trial 1 finished with value: 123.10885862042862 and parameters: {'regression_mode': 'ols', 'ridge_alpha': 1.7718847354806828, 'fit_intercept': False, 'include_bias': False}. Best is trial 0 with value: 121.89379310210032.
uncobre_study [validation_projected_mse]:   7%|▋         | 2/30 [00:00<00:00, 33.06trial/s, best=121.894, objective=123.109][I 2026-03-28 07:41:08,925] Trial 2 finished with value: 122.18100462565796 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 0.006690421166498805, 'fit_intercept': True, 'include_bias': True}. Best is trial 0 with value: 121.89379310210032.
uncobre_study [validation_projected_mse]:  10%|█         | 3/30 [00:00<00:00, 37.91trial/s, best=121.894, objective=122.181][I 2026-03-28 07:41:08,991] Trial 3 finished with value: 122.17528183596723 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 0.01578232781079559, 'fit_intercept': False, 'include_bias': True}. Best is trial 0 with value: 121.89379310210032.
uncobre_study [validation_projected_mse]:  13%|█▎        | 4/30 [00:00<00:00, 27.50trial/s, best=121.894, objective=122.175][I 2026-03-28 07:41:09,039] Trial 4 finished with value: 122.18181196852574 and parameters: {'regression_mode': 'ols', 'ridge_alpha': 0.4418441521199725, 'fit_intercept': True, 'include_bias': True}. Best is trial 0 with value: 121.89379310210032.
uncobre_study [validation_projected_mse]:  17%|█▋        | 5/30 [00:00<00:00, 27.50trial/s, best=121.894, objective=122.182][I 2026-03-28 07:41:09,089] Trial 5 finished with value: 122.18181196852574 and parameters: {'regression_mode': 'ols', 'ridge_alpha': 0.0003855073690026182, 'fit_intercept': True, 'include_bias': True}. Best is trial 0 with value: 121.89379310210032.
uncobre_study [validation_projected_mse]:  20%|██        | 6/30 [00:00<00:00, 27.50trial/s, best=121.894, objective=122.182][I 2026-03-28 07:41:09,117] Trial 6 finished with value: 122.18138114214112 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 0.003570095960030952, 'fit_intercept': True, 'include_bias': True}. Best is trial 0 with value: 121.89379310210032.
uncobre_study [validation_projected_mse]:  23%|██▎       | 7/30 [00:00<00:00, 25.40trial/s, best=121.894, objective=122.181][I 2026-03-28 07:41:09,128] Trial 7 finished with value: 121.67298489972383 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 4.475040191350905, 'fit_intercept': True, 'include_bias': True}. Best is trial 7 with value: 121.67298489972383.
uncobre_study [validation_projected_mse]:  27%|██▋       | 8/30 [00:00<00:00, 25.40trial/s, best=121.673, objective=121.673][I 2026-03-28 07:41:09,141] Trial 8 finished with value: 122.18173461664674 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 0.00018679434894556328, 'fit_intercept': False, 'include_bias': True}. Best is trial 7 with value: 121.67298489972383.
uncobre_study [validation_projected_mse]:  30%|███       | 9/30 [00:00<00:00, 25.40trial/s, best=121.673, objective=122.182][I 2026-03-28 07:41:09,190] Trial 9 finished with value: 122.18181196852584 and parameters: {'regression_mode': 'ols', 'ridge_alpha': 0.18037506431281855, 'fit_intercept': False, 'include_bias': True}. Best is trial 7 with value: 121.67298489972383.
uncobre_study [validation_projected_mse]:  33%|███▎      | 10/30 [00:00<00:00, 25.40trial/s, best=121.673, objective=122.182][I 2026-03-28 07:41:09,298] Trial 10 finished with value: 119.73172601286537 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 32.48850665036816, 'fit_intercept': True, 'include_bias': False}. Best is trial 10 with value: 119.73172601286537.
uncobre_study [validation_projected_mse]:  37%|███▋      | 11/30 [00:00<00:00, 23.64trial/s, best=119.732, objective=119.732][I 2026-03-28 07:41:09,353] Trial 11 finished with value: 119.6542232688924 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 34.812819742425035, 'fit_intercept': True, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  40%|████      | 12/30 [00:00<00:00, 23.64trial/s, best=119.654, objective=119.654][I 2026-03-28 07:41:09,420] Trial 12 finished with value: 120.8785645599219 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 96.12772885103645, 'fit_intercept': True, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  43%|████▎     | 13/30 [00:00<00:00, 23.64trial/s, best=119.654, objective=120.879][I 2026-03-28 07:41:09,533] Trial 13 finished with value: 120.49661410029442 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 89.40904698855452, 'fit_intercept': True, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  47%|████▋     | 14/30 [00:00<00:00, 18.24trial/s, best=119.654, objective=120.497][I 2026-03-28 07:41:09,565] Trial 14 finished with value: 120.62649501535284 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 16.0680733979222, 'fit_intercept': True, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  50%|█████     | 15/30 [00:00<00:00, 18.24trial/s, best=119.654, objective=120.626][I 2026-03-28 07:41:09,580] Trial 15 finished with value: 120.62446570943968 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 16.095338840523358, 'fit_intercept': True, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  53%|█████▎    | 16/30 [00:00<00:00, 18.24trial/s, best=119.654, objective=120.624][I 2026-03-28 07:41:09,623] Trial 16 finished with value: 120.70366734681411 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 15.049850806957354, 'fit_intercept': True, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  57%|█████▋    | 17/30 [00:00<00:00, 18.24trial/s, best=119.654, objective=120.704][I 2026-03-28 07:41:09,636] Trial 17 finished with value: 122.17673640947487 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 0.04208058528570935, 'fit_intercept': True, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  60%|██████    | 18/30 [00:00<00:00, 23.17trial/s, best=119.654, objective=122.177][I 2026-03-28 07:41:09,667] Trial 18 finished with value: 123.10885862042862 and parameters: {'regression_mode': 'ols', 'ridge_alpha': 0.9559574710535295, 'fit_intercept': False, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  63%|██████▎   | 19/30 [00:00<00:00, 23.17trial/s, best=119.654, objective=123.109][I 2026-03-28 07:41:09,761] Trial 19 finished with value: 119.92442378404874 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 27.7781298082327, 'fit_intercept': True, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  67%|██████▋   | 20/30 [00:00<00:00, 23.17trial/s, best=119.654, objective=119.924][I 2026-03-28 07:41:09,774] Trial 20 finished with value: 121.6598473485279 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 4.598199349514253, 'fit_intercept': True, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  70%|███████   | 21/30 [00:00<00:00, 22.73trial/s, best=119.654, objective=121.66] [I 2026-03-28 07:41:09,786] Trial 21 finished with value: 119.81493304466818 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 30.30694351657289, 'fit_intercept': True, 'include_bias': False}. Best is trial 11 with value: 119.6542232688924.
uncobre_study [validation_projected_mse]:  73%|███████▎  | 22/30 [00:00<00:00, 22.73trial/s, best=119.654, objective=119.815][I 2026-03-28 07:41:09,800] Trial 22 finished with value: 119.51162699100283 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 40.477512775105176, 'fit_intercept': True, 'include_bias': False}. Best is trial 22 with value: 119.51162699100283.
uncobre_study [validation_projected_mse]:  77%|███████▋  | 23/30 [00:00<00:00, 22.73trial/s, best=119.512, objective=119.512][I 2026-03-28 07:41:09,811] Trial 23 finished with value: 121.38029143644455 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 7.327090305468893, 'fit_intercept': True, 'include_bias': False}. Best is trial 22 with value: 119.51162699100283.
uncobre_study [validation_projected_mse]:  80%|████████  | 24/30 [00:00<00:00, 22.73trial/s, best=119.512, objective=121.38] [I 2026-03-28 07:41:09,822] Trial 24 finished with value: 120.62507844797902 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 91.76669658365404, 'fit_intercept': True, 'include_bias': False}. Best is trial 22 with value: 119.51162699100283.
uncobre_study [validation_projected_mse]:  83%|████████▎ | 25/30 [00:00<00:00, 22.73trial/s, best=119.512, objective=120.625][I 2026-03-28 07:41:09,839] Trial 25 finished with value: 119.58321350199715 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 37.31816361602577, 'fit_intercept': True, 'include_bias': False}. Best is trial 22 with value: 119.51162699100283.
uncobre_study [validation_projected_mse]:  87%|████████▋ | 26/30 [00:00<00:00, 22.73trial/s, best=119.512, objective=119.583][I 2026-03-28 07:41:09,929] Trial 26 finished with value: 123.10885862042862 and parameters: {'regression_mode': 'ols', 'ridge_alpha': 0.598765870357825, 'fit_intercept': False, 'include_bias': False}. Best is trial 22 with value: 119.51162699100283.
uncobre_study [validation_projected_mse]:  90%|█████████ | 27/30 [00:01<00:00, 27.97trial/s, best=119.512, objective=123.109][I 2026-03-28 07:41:10,075] Trial 27 finished with value: 121.34813636559176 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 7.655300330228423, 'fit_intercept': True, 'include_bias': False}. Best is trial 22 with value: 119.51162699100283.
uncobre_study [validation_projected_mse]:  93%|█████████▎| 28/30 [00:01<00:00, 27.97trial/s, best=119.512, objective=121.348][I 2026-03-28 07:41:10,090] Trial 28 finished with value: 122.16067380913802 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 0.1755613460191761, 'fit_intercept': True, 'include_bias': False}. Best is trial 22 with value: 119.51162699100283.
uncobre_study [validation_projected_mse]:  97%|█████████▋| 29/30 [00:01<00:00, 27.97trial/s, best=119.512, objective=122.161][I 2026-03-28 07:41:10,108] Trial 29 finished with value: 122.00389433691718 and parameters: {'regression_mode': 'ridge', 'ridge_alpha': 1.503861825725788, 'fit_intercept': True, 'include_bias': False}. Best is trial 22 with value: 119.51162699100283.

UNCOBRE training complete.
Measured-output targets: COD, TSS, TN, TP, S_S, S_I, S_NH4_N, S_NO3_N, S_PO4_P, S_O2, S_Alkalinity, X_I, X_S, X_H, X_AUT
Split sizes: {'train': 8000, 'test': 2000, 'optuna_dataset': 800, 'optuna_train': 640, 'optuna_test': 160}
Saved model bundle: C:\Users\eselerio\projects\pibre-model\results\uncobre\model_20260328_074110.pkl
Saved metrics summary: C:\Users\eselerio\projects\pibre-model\results\uncobre\metrics_20260328_074110.json
Saved Optuna summary: C:\Users\eselerio\projects\pibre-model\results\uncobre\optuna_20260328_074110.json

,regression_mode,ridge_alpha,fit_intercept,include_bias,interaction_only,random_state
0,ridge,40.477513,True,False,False,42

   train  test  optuna_dataset  optuna_train  optuna_test
0   8000  2000             800           640          160

                                                           path
model_bundle  C:\Users\eselerio\projects\pibre-model\results...
metrics       C:\Users\eselerio\projects\pibre-model\results...
optuna        C:\Users\eselerio\projects\pibre-model\results...

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.818527,84.209403,9.176568,2.565598,3.261940e+07,4.912354e+02,3.792494e+03,6.698601e+01,3.790781e+03
1,projected,0.811553,84.293447,9.181146,2.579319,3.375255e+07,4.290208e-12,2.190545e-11,7.828345e-13,2.182787e-11

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.837132,87.454355,9.351703,2.643487,3.189088e+07,4.597561e+02,3.450197e+03,6.286880e+01,3.448940e+03
1,projected,0.828889,87.527967,9.355638,2.653050,3.285109e+07,4.258782e-12,1.647413e-11,7.761732e-13,1.637090e-11

,target,raw_R2,raw_MSE,raw_RMSE,raw_MAE,raw_MAPE,projected_R2,projected_MSE,projected_RMSE,projected_MAE,projected_MAPE
0,Out_COD,0.999083,2.833884,1.683414,1.199794,3.758234e-03,0.999067,2.882040e+00,1.697657,1.177729,3.700126e-03
1,Out_TSS,0.998947,2.005595,1.416190,1.037760,4.823379e-03,0.998931,2.036303e+00,1.426991,1.017857,4.754162e-03
2,Out_TN,0.994600,0.579050,0.760953,0.512618,1.697957e-02,0.994581,5.811371e-01,0.762324,0.511191,1.694906e-02
3,Out_TP,0.989514,0.072812,0.269836,0.214091,3.728421e-02,0.947340,3.656442e-01,0.604685,0.217982,4.954723e-02
4,Out_S_S,0.879759,0.631617,0.794743,0.570363,1.074250e-01,0.879113,6.350086e-01,0.796874,0.572157,1.077998e-01
5,Out_S_I,0.999975,0.009859,0.099295,0.085691,1.972125e-03,1.000000,3.902014e-07,0.000625,0.000596,1.273848e-05
6,Out_S_NH4_N,0.719121,26.549970,5.152666,3.734439,1.382990e+07,0.717931,2.666250e+01,5.163575,3.776079,1.405732e+07
7,Out_S_NO3_N,0.668977,24.149558,4.914220,3.636910,1.470557e+01,0.667361,2.426746e+01,4.926202,3.677042,1.437298e+01
8,Out_S_PO4_P,0.989917,0.073349,0.270831,0.215178,5.703790e+06,0.950180,3.624306e-01,0.602022,0.224396,2.072212e+07
9,Out_S_O2,0.963727,0.067194,0.259217,0.191598,4.064686e-02,0.963727,6.719351e-02,0.259217,0.191598,4.064686e-02
10,Out_S_Alkalinity,0.724925,1251.102628,35.370929,26.137617,4.404431e+08,0.724942,1.251025e+03,35.369831,26.129356,4.402197e+08
11,Out_X_I,0.999864,0.135990,0.368769,0.274631,2.969616e-03,0.999610,3.914180e-01,0.625634,0.413497,4.493908e-03
12,Out_X_S,-0.107809,1.100212,1.048910,0.370650,5.536609e+00,-0.145110,1.137258e+00,1.066423,0.411784,6.297953e+00
13,Out_X_H,0.999357,1.051294,1.025326,0.594480,3.711450e-03,0.999357,1.049879e+00,1.024636,0.592003,3.692416e-03
14,Out_X_AUT,0.737017,1.452313,1.205120,0.876486,1.838634e+07,0.736306,1.456241e+00,1.206748,0.882485,1.776720e+07

,count,mean,std,min,25%,50%,75%,max
raw_constraint_l2,2000.0,4.597561e+02,5.428337e+02,5.196614e+00,1.488056e+02,2.555273e+02,5.105911e+02,3.450197e+03
projected_constraint_l2,2000.0,4.258782e-12,2.452348e-12,5.684342e-14,2.574761e-12,3.827247e-12,5.617945e-12,1.647413e-11

In [7]:
import pandas as pd

from src.models.ml import load_cobre_params, run_cobre_pipeline
from src.utils.train import tune_cobre_hyperparameters

cobre_params = load_cobre_params()

cobre_hyperparameters = dict(cobre_params["training_defaults"])
cobre_optuna_summary = None
if USE_OPTUNA:
    cobre_hyperparameters, cobre_optuna_summary = tune_cobre_hyperparameters(
        tuning_dataset_splits.train,
        tuning_dataset_splits.test,
        A_matrix=A_matrix,
        model_params=cobre_params,
        tuning_epochs=int(ml_orchestration["tuning_epochs"]),
        n_trials=int(ml_orchestration["n_trials"]),
        timeout=ml_orchestration["timeout_seconds"],
    )

cobre_result = run_cobre_pipeline(
    main_dataset_splits.train,
    main_dataset_splits.test,
    A_matrix,
    model_params=cobre_params,
    model_hyperparameters=cobre_hyperparameters,
    optuna_summary=cobre_optuna_summary,
    persist_artifacts=True,
)

print("COBRE training complete.")
print(f"Measured-output targets: {', ' .join(metadata['measured_output_columns'])}")
print(f"Split sizes: {split_sizes}")
print(f"Saved model bundle: {cobre_result['artifact_paths']['model_bundle']}")
print(f"Saved metrics summary: {cobre_result['artifact_paths']['metrics']}")
print(f"Saved Optuna summary: {cobre_result['artifact_paths']['optuna']}")

display(pd.DataFrame([cobre_result["best_hyperparameters"]]))
display(pd.DataFrame([split_sizes]))
display(pd.Series(cobre_result["artifact_paths"], name="path").to_frame())
display(cobre_result["train_report"]["aggregate_metrics"])
display(cobre_result["test_report"]["aggregate_metrics"])
display(cobre_result["test_report"]["per_target_metrics"])
display(cobre_result["test_report"]["constraint_residuals"].describe().T)

[I 2026-03-28 07:41:11,063] A new study created in memory with name: cobre_study
cobre_study [validation_loss]:   0%|          | 0/30 [00:00<?, ?trial/s][I 2026-03-28 07:41:29,741] Trial 0 finished with value: 285.5869464319246 and parameters: {'learning_rate': 0.0010253509690168502, 'lambda_l1': 0.006351221010640704, 'weight_decay': 4.570563099801451e-05, 'clip_max_norm': 3.1939631788866647, 'bilinear_init_scale': 0.0002636875533972306}. Best is trial 0 with value: 285.5869464319246.
cobre_study [validation_loss]:   3%|▎         | 1/30 [00:18<09:01, 18.68s/trial, best=285.587, objective=285.587][I 2026-03-28 07:41:47,560] Trial 1 finished with value: 480.2397233773976 and parameters: {'learning_rate': 0.00026364803038431676, 'lambda_l1': 1.7073967431528114e-06, 'weight_decay': 0.00021423021757741048, 'clip_max_norm': 3.20501755284444, 'bilinear_init_scale': 0.008148293210105292}. Best is trial 0 with value: 285.5869464319246.
cobre_study [validation_loss]:   7%|▋         | 2/30 [00:36<08:28, 18.17s/trial, best=285.587, objective=480.24] [I 2026-03-28 07:42:04,358] Trial 2 finished with value: 533.5125552285172 and parameters: {'learning_rate': 0.00011364672700011186, 'lambda_l1': 0.00757947995334801, 'weight_decay': 0.00014528246637516033, 'clip_max_norm': 1.4555259980522428, 'bilinear_init_scale': 0.00030955664602423704}. Best is trial 0 with value: 285.5869464319246.
cobre_study [validation_loss]:  10%|█         | 3/30 [00:53<07:53, 17.54s/trial, best=285.587, objective=533.513][I 2026-03-28 07:42:21,439] Trial 3 finished with value: 453.93098990135184 and parameters: {'learning_rate': 0.0003126102910311062, 'lambda_l1': 1.6480446427978994e-05, 'weight_decay': 4.2051564509138674e-06, 'clip_max_norm': 2.4437525838895207, 'bilinear_init_scale': 0.0006109683510122496}. Best is trial 0 with value: 285.5869464319246.
cobre_study [validation_loss]:  13%|█▎        | 4/30 [01:10<07:31, 17.36s/trial, best=285.587, objective=453.931][I 2026-03-28 07:42:38,674] Trial 4 finished with value: 123.0836026225092 and parameters: {'learning_rate': 0.0044809759182149545, 'lambda_l1': 3.6138942712165278e-06, 'weight_decay': 2.8888383623653154e-07, 'clip_max_norm': 2.148628294821613, 'bilinear_init_scale': 0.0017018418817029183}. Best is trial 4 with value: 123.0836026225092.
cobre_study [validation_loss]:  17%|█▋        | 5/30 [01:27<07:12, 17.32s/trial, best=123.084, objective=123.084][I 2026-03-28 07:42:55,159] Trial 5 finished with value: 118.83331291648285 and parameters: {'learning_rate': 0.013157287601765641, 'lambda_l1': 6.290644294586145e-06, 'weight_decay': 3.725393839578879e-06, 'clip_max_norm': 3.165865559879191, 'bilinear_init_scale': 0.00013346527038305943}. Best is trial 5 with value: 118.83331291648285.
cobre_study [validation_loss]:  20%|██        | 6/30 [01:44<06:48, 17.03s/trial, best=118.833, objective=118.833][I 2026-03-28 07:43:11,424] Trial 6 finished with value: 123.66678155695047 and parameters: {'learning_rate': 0.004362599362560562, 'lambda_l1': 4.809461967501575e-06, 'weight_decay': 2.1147447960615646e-08, 'clip_max_norm': 4.7699849176399995, 'bilinear_init_scale': 0.04038423798071561}. Best is trial 5 with value: 118.83331291648285.
cobre_study [validation_loss]:  23%|██▎       | 7/30 [02:00<06:25, 16.78s/trial, best=118.833, objective=123.667][I 2026-03-28 07:43:27,616] Trial 7 finished with value: 118.9748164282183 and parameters: {'learning_rate': 0.015199881220083977, 'lambda_l1': 1.6536937182824424e-05, 'weight_decay': 3.078651783619614e-08, 'clip_max_norm': 3.579048619304706, 'bilinear_init_scale': 0.0015415527060141947}. Best is trial 5 with value: 118.83331291648285.
cobre_study [validation_loss]:  27%|██▋       | 8/30 [02:16<06:05, 16.59s/trial, best=118.833, objective=118.975][I 2026-03-28 07:43:28,295] Trial 8 pruned.
cobre_study [validation_loss]:  30%|███       | 9/30 [02:17<04:03, 11.62s/trial, best=118.833, objective=596.158][I 2026-03-28 07:43:45,221] Trial 9 finished with value: 119.94486660647415 and parameters: {'learning_rate': 0.0061394260508981545, 'lambda_l1': 1.7654048052495086e-05, 'weight_decay': 3.984190594434684e-06, 'clip_max_norm': 2.9601962570447586, 'bilinear_init_scale': 0.0003154399030833099}. Best is trial 5 with value: 118.83331291648285.
cobre_study [validation_loss]:  33%|███▎      | 10/30 [02:34<04:25, 13.26s/trial, best=118.833, objective=119.945][I 2026-03-28 07:44:01,546] Trial 10 finished with value: 118.1858014661632 and parameters: {'learning_rate': 0.04274146035016711, 'lambda_l1': 0.0006302314035822053, 'weight_decay': 3.956459114059686e-07, 'clip_max_norm': 0.5808284402666901, 'bilinear_init_scale': 0.0001094388225329257}. Best is trial 10 with value: 118.1858014661632.
cobre_study [validation_loss]:  37%|███▋      | 11/30 [02:50<04:29, 14.20s/trial, best=118.186, objective=118.186][I 2026-03-28 07:44:18,462] Trial 11 finished with value: 118.01125534665098 and parameters: {'learning_rate': 0.0334385416496932, 'lambda_l1': 0.0008052667117094477, 'weight_decay': 4.292408798340347e-07, 'clip_max_norm': 0.88513280783595, 'bilinear_init_scale': 0.00010234297699939819}. Best is trial 11 with value: 118.01125534665098.
cobre_study [validation_loss]:  40%|████      | 12/30 [03:07<04:30, 15.02s/trial, best=118.011, objective=118.011][I 2026-03-28 07:44:36,493] Trial 12 finished with value: 118.04945622268065 and parameters: {'learning_rate': 0.047688476542572876, 'lambda_l1': 0.0009762852978975716, 'weight_decay': 2.687023979812976e-07, 'clip_max_norm': 0.6518352538428379, 'bilinear_init_scale': 0.0001107538224550815}. Best is trial 11 with value: 118.01125534665098.
cobre_study [validation_loss]:  43%|████▎     | 13/30 [03:25<04:30, 15.93s/trial, best=118.011, objective=118.049][I 2026-03-28 07:44:55,409] Trial 13 finished with value: 118.13811889459369 and parameters: {'learning_rate': 0.04148354759012513, 'lambda_l1': 0.0008573153133944766, 'weight_decay': 2.8990308980212035e-07, 'clip_max_norm': 0.535207608597128, 'bilinear_init_scale': 0.0055353764351862775}. Best is trial 11 with value: 118.01125534665098.
cobre_study [validation_loss]:  47%|████▋     | 14/30 [03:44<04:29, 16.84s/trial, best=118.011, objective=118.138][I 2026-03-28 07:45:12,633] Trial 14 finished with value: 118.39226222892694 and parameters: {'learning_rate': 0.01825156401523368, 'lambda_l1': 0.0009700167315785776, 'weight_decay': 9.768182991595732e-08, 'clip_max_norm': 1.3090203277118488, 'bilinear_init_scale': 0.00011850112282867767}. Best is trial 11 with value: 118.01125534665098.
cobre_study [validation_loss]:  50%|█████     | 15/30 [04:01<04:14, 16.95s/trial, best=118.011, objective=118.392][I 2026-03-28 07:45:13,361] Trial 15 pruned.
cobre_study [validation_loss]:  53%|█████▎    | 16/30 [04:02<02:48, 12.07s/trial, best=118.011, objective=570.508][I 2026-03-28 07:45:30,812] Trial 16 finished with value: 117.82018308001871 and parameters: {'learning_rate': 0.04980228225761535, 'lambda_l1': 0.0028277656800386416, 'weight_decay': 8.151747572977058e-07, 'clip_max_norm': 1.8218155004114398, 'bilinear_init_scale': 0.040360784578029475}. Best is trial 16 with value: 117.82018308001871.
cobre_study [validation_loss]:  57%|█████▋    | 17/30 [04:19<02:57, 13.69s/trial, best=117.82, objective=117.82]  [I 2026-03-28 07:45:48,115] Trial 17 finished with value: 118.07796465618739 and parameters: {'learning_rate': 0.02419373719491524, 'lambda_l1': 0.0032788146587361964, 'weight_decay': 1.2982238064282555e-06, 'clip_max_norm': 1.941758663687275, 'bilinear_init_scale': 0.04877754947476636}. Best is trial 16 with value: 117.82018308001871.
cobre_study [validation_loss]:  60%|██████    | 18/30 [04:37<02:57, 14.77s/trial, best=117.82, objective=118.078][I 2026-03-28 07:45:48,841] Trial 18 pruned.
cobre_study [validation_loss]:  63%|██████▎   | 19/30 [04:37<01:56, 10.55s/trial, best=117.82, objective=461.609][I 2026-03-28 07:45:49,567] Trial 19 pruned.
cobre_study [validation_loss]:  67%|██████▋   | 20/30 [04:38<01:16,  7.60s/trial, best=117.82, objective=551.138][I 2026-03-28 07:46:06,692] Trial 20 finished with value: 118.52288830728571 and parameters: {'learning_rate': 0.02636078013560043, 'lambda_l1': 0.0003924504996054704, 'weight_decay': 6.938460861728772e-08, 'clip_max_norm': 2.5395719727377335, 'bilinear_init_scale': 0.01848382656601766}. Best is trial 16 with value: 117.82018308001871.
cobre_study [validation_loss]:  70%|███████   | 21/30 [04:55<01:34, 10.46s/trial, best=117.82, objective=118.523][I 2026-03-28 07:46:24,072] Trial 21 finished with value: 117.87993942499438 and parameters: {'learning_rate': 0.033318994877239355, 'lambda_l1': 0.0019333887651959004, 'weight_decay': 8.8418472552369e-07, 'clip_max_norm': 0.9559863649118943, 'bilinear_init_scale': 0.0010503281634433724}. Best is trial 16 with value: 117.82018308001871.
cobre_study [validation_loss]:  73%|███████▎  | 22/30 [05:13<01:40, 12.54s/trial, best=117.82, objective=117.88] [I 2026-03-28 07:46:24,832] Trial 22 pruned.
cobre_study [validation_loss]:  77%|███████▋  | 23/30 [05:13<01:03,  9.00s/trial, best=117.82, objective=439.62][I 2026-03-28 07:46:42,368] Trial 23 finished with value: 118.12773841848994 and parameters: {'learning_rate': 0.029231563019008335, 'lambda_l1': 0.0019058181183396962, 'weight_decay': 1.3564211964165484e-05, 'clip_max_norm': 1.6299923549182558, 'bilinear_init_scale': 0.003049088555335681}. Best is trial 16 with value: 117.82018308001871.
cobre_study [validation_loss]:  80%|████████  | 24/30 [05:31<01:09, 11.56s/trial, best=117.82, objective=118.128][I 2026-03-28 07:46:59,612] Trial 24 finished with value: 116.3134892011495 and parameters: {'learning_rate': 0.049886201613734575, 'lambda_l1': 0.009593920279772027, 'weight_decay': 1.0311008280191087e-07, 'clip_max_norm': 0.965680552480618, 'bilinear_init_scale': 0.013957004687835669}. Best is trial 24 with value: 116.3134892011495.
cobre_study [validation_loss]:  83%|████████▎ | 25/30 [05:48<01:06, 13.27s/trial, best=116.313, objective=116.313][I 2026-03-28 07:47:00,341] Trial 25 pruned.
cobre_study [validation_loss]:  87%|████████▋ | 26/30 [05:49<00:38,  9.51s/trial, best=116.313, objective=328.085][I 2026-03-28 07:47:01,055] Trial 26 pruned.
cobre_study [validation_loss]:  90%|█████████ | 27/30 [05:49<00:20,  6.87s/trial, best=116.313, objective=412.047][I 2026-03-28 07:47:18,125] Trial 27 finished with value: 117.56895228987725 and parameters: {'learning_rate': 0.0473647607398261, 'lambda_l1': 0.0032674620922099155, 'weight_decay': 4.9293357245314964e-08, 'clip_max_norm': 1.6089254172568563, 'bilinear_init_scale': 0.032335624034488385}. Best is trial 24 with value: 116.3134892011495.
cobre_study [validation_loss]:  93%|█████████▎| 28/30 [06:07<00:19,  9.93s/trial, best=116.313, objective=117.569][I 2026-03-28 07:47:18,837] Trial 28 pruned.
cobre_study [validation_loss]:  97%|█████████▋| 29/30 [06:07<00:07,  7.16s/trial, best=116.313, objective=353.97] [I 2026-03-28 07:47:19,548] Trial 29 pruned.

COBRE training complete.
Measured-output targets: COD, TSS, TN, TP, S_S, S_I, S_NH4_N, S_NO3_N, S_PO4_P, S_O2, S_Alkalinity, X_I, X_S, X_H, X_AUT
Split sizes: {'train': 8000, 'test': 2000, 'optuna_dataset': 800, 'optuna_train': 640, 'optuna_test': 160}
Saved model bundle: C:\Users\eselerio\projects\pibre-model\results\cobre\model_20260328_075054.pkl
Saved metrics summary: C:\Users\eselerio\projects\pibre-model\results\cobre\metrics_20260328_075054.json
Saved Optuna summary: C:\Users\eselerio\projects\pibre-model\results\cobre\optuna_20260328_075054.json

   learning_rate  lambda_l1  weight_decay  clip_max_norm  bilinear_init_scale
0       0.049886   0.009594  1.031101e-07       0.965681             0.013957

   train  test  optuna_dataset  optuna_train  optuna_test
0   8000  2000             800           640          160

                                                           path
model_bundle  C:\Users\eselerio\projects\pibre-model\results...
metrics       C:\Users\eselerio\projects\pibre-model\results...
optuna        C:\Users\eselerio\projects\pibre-model\results...

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,-2.743519,554.005289,23.537317,14.910609,4.771115e+07,6494.934979,14095.390976,1311.798268,13543.635425
1,projected,0.749449,86.843356,9.318978,2.912275,3.452223e+07,0.000360,0.000534,0.000067,0.000488

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,-6.694968,554.633101,23.550650,14.935829,4.565928e+07,6671.894590,14003.997798,1336.423101,13853.952737
1,projected,0.522379,89.461887,9.458429,2.963776,3.312216e+07,0.000357,0.000530,0.000066,0.000482

,target,raw_R2,raw_MSE,raw_RMSE,raw_MAE,raw_MAPE,projected_R2,projected_MSE,projected_RMSE,projected_MAE,projected_MAPE
0,Out_COD,0.888771,343.578022,18.535858,15.213831,4.756330e-02,0.997908,6.463515e+00,2.542344,1.806537,5.594634e-03
1,Out_TSS,0.910356,170.718889,13.065944,10.632149,4.729823e-02,0.998348,3.145202e+00,1.773472,1.331784,6.197235e-03
2,Out_TN,0.673649,34.998071,5.915917,4.778556,1.485677e-01,0.991104,9.540466e-01,0.976753,0.692675,2.207719e-02
3,Out_TP,-3.578266,31.789058,5.638179,4.988868,6.311419e-01,0.948242,3.593830e-01,0.599486,0.225445,5.052502e-02
4,Out_S_S,-14.714827,82.548903,9.085643,7.723759,1.606417e+00,-0.048188,5.506062e+00,2.346500,1.474032,2.979727e-01
5,Out_S_I,-7.576796,3440.050879,58.651947,55.135533,9.994663e-01,1.000000,3.877445e-07,0.000623,0.000594,1.269875e-05
6,Out_S_NH4_N,-8.517474,899.635636,29.993927,28.191687,1.090426e+08,0.714098,2.702475e+01,5.198533,3.801013,1.351217e+07
7,Out_S_NO3_N,-10.829947,863.045541,29.377637,27.726586,6.516406e+01,0.663150,2.457469e+01,4.957287,3.699103,1.410966e+01
8,Out_S_PO4_P,-2.561148,25.906566,5.089849,4.311573,1.623818e+07,0.951479,3.529776e-01,0.594119,0.233755,2.031856e+07
9,Out_S_O2,0.859806,0.259698,0.509605,0.399991,8.529120e-02,0.859806,2.596976e-01,0.509605,0.399991,8.529120e-02
10,Out_S_Alkalinity,0.705154,1341.028303,36.620053,27.090869,5.440826e+08,0.722973,1.259980e+03,35.496203,26.247749,4.425094e+08
11,Out_X_I,-0.007898,1010.633727,31.790466,26.912697,3.028790e-01,0.999323,6.790053e-01,0.824018,0.631183,6.762802e-03
12,Out_X_S,-57.309744,57.909868,7.609853,6.299905,1.035666e+02,-3.506546,4.475641e+00,2.115571,1.216959,1.923573e+01
13,Out_X_H,0.993952,9.882192,3.143595,2.410390,1.561037e-02,0.996540,5.653741e+00,2.377760,1.471532,9.342779e-03
14,Out_X_AUT,-0.360111,7.511165,2.740650,2.221045,1.552574e+07,0.547451,2.499185e+00,1.580881,1.224289,2.049221e+07

,count,mean,std,min,25%,50%,75%,max
raw_constraint_l2,2000.0,6671.894590,2880.137005,1398.508844,4168.016907,6236.602432,9082.892062,14003.997798
projected_constraint_l2,2000.0,0.000357,0.000087,0.000146,0.000293,0.000353,0.000430,0.000530

## Additional Measured-Space Regressors

The notebook now owns the main train-test split and the optional Optuna subset used for hyperparameter optimization. Run the next cell to register the available measured-space regressors, then call `run_classical_regressor(...)` with `use_optuna=True` to tune on the notebook-managed subset or `use_optuna=False` to train with each model's `training_defaults`.

In [ ]:
import pandas as pd

from src.models.ml import (
    load_adaboost_regressor_params,
    load_catboost_regressor_params,
    load_lightgbm_regressor_params,
    load_random_forest_regressor_params,
    load_svr_regressor_params,
    load_xgboost_regressor_params,
    run_adaboost_regressor_pipeline,
    run_catboost_regressor_pipeline,
    run_lightgbm_regressor_pipeline,
    run_random_forest_regressor_pipeline,
    run_svr_regressor_pipeline,
    run_xgboost_regressor_pipeline,
)
from src.models.ml.adaboost_regressor import build_adaboost_regressor_model
from src.models.ml.catboost_regressor import build_catboost_regressor_model
from src.models.ml.lightgbm_regressor import build_lightgbm_regressor_model
from src.models.ml.random_forest_regressor import build_random_forest_regressor_model
from src.models.ml.svr_regressor import build_svr_regressor_model
from src.models.ml.xgboost_regressor import build_xgboost_regressor_model
from src.utils.train import tune_tabular_regressor_hyperparameters

classical_regressor_specs = {
    "xgboost_regressor": {
        "load_params": load_xgboost_regressor_params,
        "build_model": build_xgboost_regressor_model,
        "runner": run_xgboost_regressor_pipeline,
    },
    "lightgbm_regressor": {
        "load_params": load_lightgbm_regressor_params,
        "build_model": build_lightgbm_regressor_model,
        "runner": run_lightgbm_regressor_pipeline,
    },
    "catboost_regressor": {
        "load_params": load_catboost_regressor_params,
        "build_model": build_catboost_regressor_model,
        "runner": run_catboost_regressor_pipeline,
    },
    "adaboost_regressor": {
        "load_params": load_adaboost_regressor_params,
        "build_model": build_adaboost_regressor_model,
        "runner": run_adaboost_regressor_pipeline,
    },
    "random_forest_regressor": {
        "load_params": load_random_forest_regressor_params,
        "build_model": build_random_forest_regressor_model,
        "runner": run_random_forest_regressor_pipeline,
    },
    "svr_regressor": {
        "load_params": load_svr_regressor_params,
        "build_model": build_svr_regressor_model,
        "runner": run_svr_regressor_pipeline,
    },
}

def run_classical_regressor(
    model_name: str,
    *,
    use_optuna: bool = True,
    persist_artifacts: bool = True,
):
    spec = classical_regressor_specs[model_name]
    model_params = spec["load_params"]()
    selected_hyperparameters = dict(model_params["training_defaults"])
    optuna_summary = None

    if use_optuna:
        selected_hyperparameters, optuna_summary = tune_tabular_regressor_hyperparameters(
            model_name,
            spec["build_model"],
            tuning_dataset_splits.train,
            tuning_dataset_splits.test,
            A_matrix=A_matrix,
            model_params=model_params,
            n_trials=int(ml_orchestration["n_trials"]),
            timeout=ml_orchestration["timeout_seconds"],
        )

    result = spec["runner"](
        main_dataset_splits.train,
        main_dataset_splits.test,
        A_matrix,
        model_params=model_params,
        model_hyperparameters=selected_hyperparameters,
        optuna_summary=optuna_summary,
        persist_artifacts=persist_artifacts,
    )

    print(f"{model_name} training complete.")
    print(f"Saved model bundle: {result['artifact_paths']['model_bundle']}")
    print(f"Saved metrics summary: {result['artifact_paths']['metrics']}")
    print(f"Saved Optuna summary: {result['artifact_paths']['optuna']}")
    display(pd.DataFrame([result["best_hyperparameters"]]))
    display(result["train_report"]["aggregate_metrics"])
    display(result["test_report"]["aggregate_metrics"])
    display(result["test_report"]["per_target_metrics"])
    display(result["test_report"]["constraint_residuals"].describe().T)

    return result

classical_regressor_results = {}

for model_name in classical_regressor_specs:
    print(f"\n=== Running {model_name} ===")
    classical_regressor_results[model_name] = run_classical_regressor(
        model_name,
        use_optuna=USE_OPTUNA,
        persist_artifacts=True,
    )

list(classical_regressor_results)

=== Running xgboost_regressor ===

[I 2026-03-28 07:50:55,480] A new study created in memory with name: xgboost_regressor_study
xgboost_regressor_study [validation_mse]:   0%|          | 0/30 [00:00<?, ?trial/s][I 2026-03-28 07:51:00,205] Trial 0 finished with value: 108.0487329274031 and parameters: {'n_estimators': 170, 'learning_rate': 0.17254716573280354, 'max_depth': 7, 'min_child_weight': 2.6292183092620927, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.662397808134481, 'reg_alpha': 2.231010801867921e-06, 'reg_lambda': 2.9154431891537547}. Best is trial 0 with value: 108.0487329274031.
xgboost_regressor_study [validation_mse]:   3%|▎         | 1/30 [00:04<02:16,  4.71s/trial, best=108.049, objective=108.049][I 2026-03-28 07:51:01,367] Trial 1 finished with value: 108.1727511931725 and parameters: {'n_estimators': 224, 'learning_rate': 0.08341106432362087, 'max_depth': 3, 'min_child_weight': 7.3596614801167854, 'subsample': 0.9329770563201687, 'colsample_bytree': 0.6849356442713105, 'reg_alpha': 1.2329623163659841e-05, 'reg_lambda': 0.00541524411940254}. Best is trial 0 with value: 108.0487329274031.
xgboost_regressor_study [validation_mse]:   7%|▋         | 2/30 [00:05<01:13,  2.62s/trial, best=108.049, objective=108.173][I 2026-03-28 07:51:02,923] Trial 2 finished with value: 94.61743547522583 and parameters: {'n_estimators': 153, 'learning_rate': 0.048164145309070844, 'max_depth': 5, 'min_child_weight': 1.1211012365328634, 'subsample': 0.8447411578889518, 'colsample_bytree': 0.6557975442608167, 'reg_alpha': 5.6606706992588835e-05, 'reg_lambda': 0.029204338471814112}. Best is trial 2 with value: 94.61743547522583.
xgboost_regressor_study [validation_mse]:  10%|█         | 3/30 [00:07<00:57,  2.14s/trial, best=94.6174, objective=94.6174][I 2026-03-28 07:51:04,289] Trial 3 finished with value: 98.62328417517091 and parameters: {'n_estimators': 189, 'learning_rate': 0.10508421338691762, 'max_depth': 4, 'min_child_weight': 2.0805107656418516, 'subsample': 0.836965827544817, 'colsample_bytree': 0.6185801650879991, 'reg_alpha': 0.0044184415211997235, 'reg_lambda': 0.004809461967501573}. Best is trial 2 with value: 94.61743547522583.
xgboost_regressor_study [validation_mse]:  13%|█▎        | 4/30 [00:08<00:47,  1.83s/trial, best=94.6174, objective=98.6233][I 2026-03-28 07:51:05,948] Trial 4 finished with value: 132.2891606472144 and parameters: {'n_estimators': 95, 'learning_rate': 0.17160445029754812, 'max_depth': 8, 'min_child_weight': 4.703026275515195, 'subsample': 0.7218455076693483, 'colsample_bytree': 0.6390688456025535, 'reg_alpha': 0.012746711578215055, 'reg_lambda': 0.057624872164786026}. Best is trial 2 with value: 94.61743547522583.
xgboost_regressor_study [validation_mse]:  17%|█▋        | 5/30 [00:10<00:44,  1.77s/trial, best=94.6174, objective=132.289][I 2026-03-28 07:51:06,708] Trial 5 finished with value: 115.73058150431477 and parameters: {'n_estimators': 109, 'learning_rate': 0.04407984038169244, 'max_depth': 3, 'min_child_weight': 6.221582596639011, 'subsample': 0.7035119926400067, 'colsample_bytree': 0.8650089137415928, 'reg_alpha': 7.417652034871826e-05, 'reg_lambda': 0.12030178871154672}. Best is trial 2 with value: 94.61743547522583.
xgboost_regressor_study [validation_mse]:  20%|██        | 6/30 [00:11<00:34,  1.43s/trial, best=94.6174, objective=115.731][I 2026-03-28 07:51:11,311] Trial 6 finished with value: 96.37737719082735 and parameters: {'n_estimators': 211, 'learning_rate': 0.017398074711291726, 'max_depth': 8, 'min_child_weight': 4.288672925586801, 'subsample': 0.9757995766256756, 'colsample_bytree': 0.9579309401710595, 'reg_alpha': 0.003867228849117745, 'reg_lambda': 4.869640941520899}. Best is trial 2 with value: 94.61743547522583.
xgboost_regressor_study [validation_mse]:  23%|██▎       | 7/30 [00:15<00:56,  2.46s/trial, best=94.6174, objective=96.3774][I 2026-03-28 07:51:11,987] Trial 7 finished with value: 169.65575711791405 and parameters: {'n_estimators': 101, 'learning_rate': 0.017987863473362915, 'max_depth': 3, 'min_child_weight': 1.2322724997515322, 'subsample': 0.7554709158757928, 'colsample_bytree': 0.7085396127095583, 'reg_alpha': 0.09384800715909536, 'reg_lambda': 0.026730883107816707}. Best is trial 2 with value: 94.61743547522583.
xgboost_regressor_study [validation_mse]:  27%|██▋       | 8/30 [00:16<00:41,  1.90s/trial, best=94.6174, objective=169.656][I 2026-03-28 07:51:12,968] Trial 8 finished with value: 115.6040280243056 and parameters: {'n_estimators': 147, 'learning_rate': 0.05082341959721458, 'max_depth': 3, 'min_child_weight': 4.622867212183828, 'subsample': 0.6298202574719083, 'colsample_bytree': 0.9947547746402069, 'reg_alpha': 0.04300001586162608, 'reg_lambda': 0.0062353771356731605}. Best is trial 2 with value: 94.61743547522583.
xgboost_regressor_study [validation_mse]:  30%|███       | 9/30 [00:17<00:33,  1.61s/trial, best=94.6174, objective=115.604][I 2026-03-28 07:51:14,754] Trial 9 finished with value: 118.91689731243326 and parameters: {'n_estimators': 81, 'learning_rate': 0.11506408247250169, 'max_depth': 7, 'min_child_weight': 3.773828004005622, 'subsample': 0.9085081386743783, 'colsample_bytree': 0.6296178606936361, 'reg_alpha': 0.0001415123591905371, 'reg_lambda': 0.0029072088906598446}. Best is trial 2 with value: 94.61743547522583.
xgboost_regressor_study [validation_mse]:  33%|███▎      | 10/30 [00:19<00:33,  1.66s/trial, best=94.6174, objective=118.917][I 2026-03-28 07:51:18,075] Trial 10 finished with value: 109.79642406495344 and parameters: {'n_estimators': 288, 'learning_rate': 0.010181283131439643, 'max_depth': 5, 'min_child_weight': 0.5255309012886331, 'subsample': 0.8277250010609204, 'colsample_bytree': 0.7772319187202809, 'reg_alpha': 0.5736202516305239, 'reg_lambda': 0.4649787443091593}. Best is trial 2 with value: 94.61743547522583.
xgboost_regressor_study [validation_mse]:  37%|███▋      | 11/30 [00:22<00:41,  2.17s/trial, best=94.6174, objective=109.796][I 2026-03-28 07:51:22,213] Trial 11 finished with value: 93.57100569753344 and parameters: {'n_estimators': 235, 'learning_rate': 0.02525611096184472, 'max_depth': 6, 'min_child_weight': 1.0558094147172983, 'subsample': 0.9850231831978604, 'colsample_bytree': 0.9499856595509167, 'reg_alpha': 0.0006859367003186782, 'reg_lambda': 5.985592563875759}. Best is trial 11 with value: 93.57100569753344.
xgboost_regressor_study [validation_mse]:  40%|████      | 12/30 [00:26<00:49,  2.77s/trial, best=93.571, objective=93.571]  [I 2026-03-28 07:51:26,534] Trial 12 finished with value: 89.74401491720145 and parameters: {'n_estimators': 263, 'learning_rate': 0.037243422013756265, 'max_depth': 6, 'min_child_weight': 1.0993719791607444, 'subsample': 0.883430193954917, 'colsample_bytree': 0.8758146404482569, 'reg_alpha': 0.0003644629811223246, 'reg_lambda': 0.5563013530978452}. Best is trial 12 with value: 89.74401491720145.
xgboost_regressor_study [validation_mse]:  43%|████▎     | 13/30 [00:31<00:55,  3.24s/trial, best=89.744, objective=89.744][I 2026-03-28 07:51:31,777] Trial 13 finished with value: 86.18268045386998 and parameters: {'n_estimators': 266, 'learning_rate': 0.0301510303963567, 'max_depth': 6, 'min_child_weight': 0.9385828774132219, 'subsample': 0.9956145525799184, 'colsample_bytree': 0.8938825194808143, 'reg_alpha': 0.0004253838572144549, 'reg_lambda': 1.279563748601099}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  47%|████▋     | 14/30 [00:36<01:01,  3.84s/trial, best=86.1827, objective=86.1827][I 2026-03-28 07:51:37,194] Trial 14 finished with value: 88.2791230175365 and parameters: {'n_estimators': 298, 'learning_rate': 0.029391456795476657, 'max_depth': 6, 'min_child_weight': 0.6639492818163223, 'subsample': 0.8987453277869946, 'colsample_bytree': 0.8884404511750978, 'reg_alpha': 0.0005925002670235801, 'reg_lambda': 0.896176122522625}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  50%|█████     | 15/30 [00:41<01:04,  4.32s/trial, best=86.1827, objective=88.2791][I 2026-03-28 07:51:46,775] Trial 15 finished with value: 92.48723194098464 and parameters: {'n_estimators': 320, 'learning_rate': 0.027449280078391973, 'max_depth': 7, 'min_child_weight': 0.634899164035148, 'subsample': 0.9488526802251774, 'colsample_bytree': 0.8642403294807579, 'reg_alpha': 0.0020223945521044367, 'reg_lambda': 1.0138114683601502}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  53%|█████▎    | 16/30 [00:51<01:22,  5.90s/trial, best=86.1827, objective=92.4872][I 2026-03-28 07:51:51,473] Trial 16 finished with value: 91.01908333245032 and parameters: {'n_estimators': 282, 'learning_rate': 0.0681107800180524, 'max_depth': 6, 'min_child_weight': 0.7216887624890409, 'subsample': 0.9997170973497533, 'colsample_bytree': 0.8034335903188419, 'reg_alpha': 2.2702911903721253e-05, 'reg_lambda': 0.21883855220822562}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  57%|█████▋    | 17/30 [00:55<01:12,  5.54s/trial, best=86.1827, objective=91.0191][I 2026-03-28 07:51:55,535] Trial 17 finished with value: 90.2965148215075 and parameters: {'n_estimators': 318, 'learning_rate': 0.029254163952999606, 'max_depth': 5, 'min_child_weight': 0.8167663198963707, 'subsample': 0.8887781922242812, 'colsample_bytree': 0.9146304965871641, 'reg_alpha': 1.1997072580708852e-06, 'reg_lambda': 1.6342817756341557}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  60%|██████    | 18/30 [01:00<01:01,  5.10s/trial, best=86.1827, objective=90.2965][I 2026-03-28 07:51:58,021] Trial 18 finished with value: 112.7571186804901 and parameters: {'n_estimators': 279, 'learning_rate': 0.014466122417259714, 'max_depth': 4, 'min_child_weight': 1.5741368644453677, 'subsample': 0.774439933428912, 'colsample_bytree': 0.8027105027486668, 'reg_alpha': 0.0007693966243533264, 'reg_lambda': 9.700882997069554}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  63%|██████▎   | 19/30 [01:02<00:47,  4.31s/trial, best=86.1827, objective=112.757][I 2026-03-28 07:52:05,709] Trial 19 finished with value: 101.21077627819415 and parameters: {'n_estimators': 253, 'learning_rate': 0.022057864661585158, 'max_depth': 7, 'min_child_weight': 0.5006965107965708, 'subsample': 0.9380393421794467, 'colsample_bytree': 0.73964158693172, 'reg_alpha': 6.577912329128825e-06, 'reg_lambda': 0.3168600847016313}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  67%|██████▋   | 20/30 [01:10<00:53,  5.33s/trial, best=86.1827, objective=101.211][I 2026-03-28 07:52:11,030] Trial 20 finished with value: 91.2398890970622 and parameters: {'n_estimators': 294, 'learning_rate': 0.034751436801011545, 'max_depth': 6, 'min_child_weight': 0.8738481357740677, 'subsample': 0.8704439901788259, 'colsample_bytree': 0.8351768488743017, 'reg_alpha': 0.00023408827083639555, 'reg_lambda': 1.497208692799015}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  70%|███████   | 21/30 [01:15<00:47,  5.32s/trial, best=86.1827, objective=91.2399][I 2026-03-28 07:52:16,689] Trial 21 finished with value: 90.87303374456863 and parameters: {'n_estimators': 252, 'learning_rate': 0.036305133297849415, 'max_depth': 6, 'min_child_weight': 1.5074840221222712, 'subsample': 0.9043821002842776, 'colsample_bytree': 0.8962639526400515, 'reg_alpha': 0.00033391821371053126, 'reg_lambda': 0.7720478502271276}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  73%|███████▎  | 22/30 [01:21<00:43,  5.42s/trial, best=86.1827, objective=90.873] [I 2026-03-28 07:52:21,117] Trial 22 finished with value: 88.34133086326668 and parameters: {'n_estimators': 256, 'learning_rate': 0.03800184388995421, 'max_depth': 6, 'min_child_weight': 0.9281638651861402, 'subsample': 0.798466209767023, 'colsample_bytree': 0.9107469916435743, 'reg_alpha': 0.0008648234410108671, 'reg_lambda': 0.6326322581799335}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  77%|███████▋  | 23/30 [01:25<00:35,  5.13s/trial, best=86.1827, objective=88.3413][I 2026-03-28 07:52:26,007] Trial 23 finished with value: 92.81814744231036 and parameters: {'n_estimators': 307, 'learning_rate': 0.059116643163038496, 'max_depth': 5, 'min_child_weight': 0.645782476244336, 'subsample': 0.7935718373672624, 'colsample_bytree': 0.9346589987012075, 'reg_alpha': 0.01643370189998826, 'reg_lambda': 2.418971603067848}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  80%|████████  | 24/30 [01:30<00:30,  5.06s/trial, best=86.1827, objective=92.8181][I 2026-03-28 07:52:34,769] Trial 24 finished with value: 89.72738189810515 and parameters: {'n_estimators': 241, 'learning_rate': 0.02111158639905033, 'max_depth': 7, 'min_child_weight': 0.892860039351107, 'subsample': 0.7440445567930714, 'colsample_bytree': 0.9854596180860138, 'reg_alpha': 0.0016618440115695248, 'reg_lambda': 0.1778603801835928}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  83%|████████▎ | 25/30 [01:39<00:30,  6.17s/trial, best=86.1827, objective=89.7274][I 2026-03-28 07:52:42,352] Trial 25 finished with value: 98.3379531322195 and parameters: {'n_estimators': 275, 'learning_rate': 0.013469303979404221, 'max_depth': 6, 'min_child_weight': 1.5394306176531711, 'subsample': 0.8136336828729006, 'colsample_bytree': 0.8369982976657244, 'reg_alpha': 3.934271817733319e-05, 'reg_lambda': 0.07814643665617312}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  87%|████████▋ | 26/30 [01:46<00:26,  6.59s/trial, best=86.1827, objective=98.338] [I 2026-03-28 07:52:45,174] Trial 26 finished with value: 98.55791377231937 and parameters: {'n_estimators': 265, 'learning_rate': 0.031666567714865194, 'max_depth': 4, 'min_child_weight': 2.046879481300489, 'subsample': 0.9533488556444156, 'colsample_bytree': 0.9036007400787756, 'reg_alpha': 0.007654595674276157, 'reg_lambda': 0.561929021626339}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  90%|█████████ | 27/30 [01:49<00:16,  5.46s/trial, best=86.1827, objective=98.5579][I 2026-03-28 07:52:48,147] Trial 27 finished with value: 89.06794414276192 and parameters: {'n_estimators': 211, 'learning_rate': 0.042806590852762345, 'max_depth': 5, 'min_child_weight': 0.63320230029317, 'subsample': 0.8612929350182127, 'colsample_bytree': 0.8380624294315939, 'reg_alpha': 0.00013181455388367374, 'reg_lambda': 1.3132816881210132}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  93%|█████████▎| 28/30 [01:52<00:09,  4.71s/trial, best=86.1827, objective=89.0679][I 2026-03-28 07:52:54,744] Trial 28 finished with value: 91.29096707380107 and parameters: {'n_estimators': 299, 'learning_rate': 0.06665492528580894, 'max_depth': 7, 'min_child_weight': 2.7440060091398397, 'subsample': 0.795848251015715, 'colsample_bytree': 0.9346671802619735, 'reg_alpha': 0.0013291364173115341, 'reg_lambda': 2.967527635851193}. Best is trial 13 with value: 86.18268045386998.
xgboost_regressor_study [validation_mse]:  97%|█████████▋| 29/30 [01:59<00:05,  5.28s/trial, best=86.1827, objective=91.291] [I 2026-03-28 07:52:59,261] Trial 29 finished with value: 94.72997551612958 and parameters: {'n_estimators': 191, 'learning_rate': 0.02331210899007277, 'max_depth': 6, 'min_child_weight': 0.9352487919687947, 'subsample': 0.9116131329133693, 'colsample_bytree': 0.9645720313621625, 'reg_alpha': 0.0005043754241450633, 'reg_lambda': 2.9528117389590407}. Best is trial 13 with value: 86.18268045386998.

xgboost_regressor training complete.
Saved model bundle: C:\Users\eselerio\projects\pibre-model\results\xgboost_regressor\model_20260328_075307.pkl
Saved metrics summary: C:\Users\eselerio\projects\pibre-model\results\xgboost_regressor\metrics_20260328_075307.json
Saved Optuna summary: C:\Users\eselerio\projects\pibre-model\results\xgboost_regressor\optuna_20260328_075307.json

,objective,n_estimators,learning_rate,max_depth,min_child_weight,subsample,colsample_bytree,reg_alpha,reg_lambda,tree_method,random_state,n_jobs,verbosity
0,reg:squarederror,266,0.030151,6,0.938583,0.995615,0.893883,0.000425,1.279564,hist,42,-1,0

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.983713,20.893452,4.570936,1.161282,1.548060e+07,4.033686e+02,4.981754e+03,6.173954e+01,4.978400e+03
1,projected,0.965792,20.665004,4.545878,1.225223,1.726993e+07,7.418923e-12,3.724828e-11,1.294351e-12,3.683454e-11

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.366557,44.474024,6.668885,1.828388,2.038444e+07,4.443362e+02,4.621675e+03,7.318765e+01,4.616143e+03
1,projected,0.518013,43.520513,6.597008,1.865772,2.204921e+07,1.098247e-11,1.504939e-10,1.789949e-12,1.500666e-10

,target,raw_R2,raw_MSE,raw_RMSE,raw_MAE,raw_MAPE,projected_R2,projected_MSE,projected_RMSE,projected_MAE,projected_MAPE
0,Out_COD,0.996780,9.946709,3.153840,2.407370,7.456642e-03,0.998146,5.728222e+00,2.393370,1.602566,4.992344e-03
1,Out_TSS,0.996411,6.834183,2.614227,2.008589,9.159831e-03,0.998303,3.231594e+00,1.797664,1.345891,6.202883e-03
2,Out_TN,0.995045,0.531372,0.728952,0.525727,1.618133e-02,0.993736,6.717731e-01,0.819618,0.609876,1.794610e-02
3,Out_TP,0.998248,0.012165,0.110296,0.084206,1.467291e-02,0.947308,3.658670e-01,0.604869,0.230712,5.121047e-02
4,Out_S_S,0.508076,2.584041,1.607495,0.089339,1.050313e-02,0.641256,1.884455e+00,1.372755,0.773890,1.558411e-01
5,Out_S_I,0.999573,0.171166,0.413722,0.312965,6.468381e-03,1.000000,3.905038e-07,0.000625,0.000596,1.275368e-05
6,Out_S_NH4_N,0.881355,11.214855,3.348859,1.670419,1.396832e+06,0.860642,1.317275e+01,3.629429,2.108731,6.990382e+06
7,Out_S_NO3_N,0.847397,11.133066,3.336625,1.854313,1.221639e+01,0.831832,1.226857e+01,3.502652,2.148567,1.371291e+01
8,Out_S_PO4_P,0.997971,0.014758,0.121482,0.090736,1.023230e+06,0.950223,3.621191e-01,0.601763,0.222940,2.069475e+07
9,Out_S_O2,0.978740,0.039382,0.198448,0.134508,2.907400e-02,0.978740,3.938172e-02,0.198448,0.134508,2.907400e-02
10,Out_S_Alkalinity,0.866884,605.440783,24.605706,14.507835,2.888412e+08,0.868349,5.987766e+02,24.469913,14.360536,2.871342e+08
11,Out_X_I,0.998617,1.386636,1.177555,0.932877,9.920045e-03,0.998888,1.115188e+00,1.056025,0.821006,8.793957e-03
12,Out_X_S,-7.410387,8.352711,2.890106,0.104168,4.188088e-01,-4.947575,5.906788e+00,2.430388,0.845935,1.255283e+01
13,Out_X_H,0.994728,8.614147,2.934987,2.171868,1.361489e-02,0.995484,7.378348e+00,2.716311,1.827157,1.142651e-02
14,Out_X_AUT,0.848911,0.834382,0.913445,0.530901,1.450525e+07,0.654865,1.905996e+00,1.380578,0.953665,1.591872e+07

,count,mean,std,min,25%,50%,75%,max
raw_constraint_l2,2000.0,4.443362e+02,6.660699e+02,1.484947e+01,1.426268e+02,2.209987e+02,3.482275e+02,4.621675e+03
projected_constraint_l2,2000.0,1.098247e-11,7.952459e-12,2.428352e-13,5.632663e-12,9.283833e-12,1.466596e-11,1.504939e-10

[I 2026-03-28 07:53:08,056] A new study created in memory with name: lightgbm_regressor_study

=== Running lightgbm_regressor ===

lightgbm_regressor_study [validation_mse]:   0%|          | 0/30 [00:00<?, ?trial/s][I 2026-03-28 07:53:09,248] Trial 0 finished with value: 106.05392364991104 and parameters: {'n_estimators': 170, 'learning_rate': 0.17254716573280354, 'num_leaves': 50, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.8832290311184181, 'colsample_bytree': 0.608233797718321, 'reg_alpha': 0.6598711072054072, 'reg_lambda': 0.6715811311069951}. Best is trial 0 with value: 106.05392364991104.
lightgbm_regressor_study [validation_mse]:   3%|▎         | 1/30 [00:01<00:34,  1.19s/trial, best=106.054, objective=106.054][I 2026-03-28 07:53:12,110] Trial 1 finished with value: 114.36882607335835 and parameters: {'n_estimators': 131, 'learning_rate': 0.017240892195821537, 'num_leaves': 23, 'max_depth': 10, 'min_child_samples': 10, 'subsample': 0.7168578594140873, 'colsample_bytree': 0.7465447373174767, 'reg_alpha': 0.0005450293694558255, 'reg_lambda': 0.3134958021096912}. Best is trial 0 with value: 106.05392364991104.
lightgbm_regressor_study [validation_mse]:   7%|▋         | 2/30 [00:04<01:00,  2.17s/trial, best=106.054, objective=114.369][I 2026-03-28 07:53:13,232] Trial 2 finished with value: 100.45484581405019 and parameters: {'n_estimators': 128, 'learning_rate': 0.04666963767236924, 'num_leaves': 44, 'max_depth': 10, 'min_child_samples': 39, 'subsample': 0.9233589392465844, 'colsample_bytree': 0.7218455076693483, 'reg_alpha': 3.855073690026181e-06, 'reg_lambda': 0.06160715952774549}. Best is trial 2 with value: 100.45484581405019.
lightgbm_regressor_study [validation_mse]:  10%|█         | 3/30 [00:05<00:45,  1.69s/trial, best=100.455, objective=100.455][I 2026-03-28 07:53:14,517] Trial 3 finished with value: 125.81869093947392 and parameters: {'n_estimators': 186, 'learning_rate': 0.014413697528610409, 'num_leaves': 39, 'max_depth': 4, 'min_child_samples': 23, 'subsample': 0.8186841117373118, 'colsample_bytree': 0.6739417822102108, 'reg_alpha': 0.6569128640939177, 'reg_lambda': 0.2666427400467688}. Best is trial 2 with value: 100.45484581405019.
lightgbm_regressor_study [validation_mse]:  13%|█▎        | 4/30 [00:06<00:39,  1.53s/trial, best=100.455, objective=125.819][I 2026-03-28 07:53:19,516] Trial 4 finished with value: 90.97876150356359 and parameters: {'n_estimators': 306, 'learning_rate': 0.1459476894296684, 'num_leaves': 44, 'max_depth': -1, 'min_child_samples': 18, 'subsample': 0.7085396127095583, 'colsample_bytree': 0.9314950036607718, 'reg_alpha': 0.00013820379228637016, 'reg_lambda': 9.258519973443786e-05}. Best is trial 4 with value: 90.97876150356359.
lightgbm_regressor_study [validation_mse]:  17%|█▋        | 5/30 [00:11<01:09,  2.78s/trial, best=90.9788, objective=90.9788][I 2026-03-28 07:53:20,740] Trial 5 finished with value: 109.18603061471389 and parameters: {'n_estimators': 210, 'learning_rate': 0.015252697030515175, 'num_leaves': 54, 'max_depth': 4, 'min_child_samples': 34, 'subsample': 0.8827429375390468, 'colsample_bytree': 0.8916028672163949, 'reg_alpha': 0.04242502238267321, 'reg_lambda': 3.298470179752566e-06}. Best is trial 4 with value: 90.97876150356359.
lightgbm_regressor_study [validation_mse]:  20%|██        | 6/30 [00:12<00:54,  2.25s/trial, best=90.9788, objective=109.186][I 2026-03-28 07:53:22,234] Trial 6 finished with value: 112.53459919676952 and parameters: {'n_estimators': 166, 'learning_rate': 0.014149761574941432, 'num_leaves': 57, 'max_depth': -1, 'min_child_samples': 31, 'subsample': 0.8550229885420852, 'colsample_bytree': 0.9548850970305306, 'reg_alpha': 0.0006812233896860299, 'reg_lambda': 6.873211713642722e-06}. Best is trial 4 with value: 90.97876150356359.
lightgbm_regressor_study [validation_mse]:  23%|██▎       | 7/30 [00:14<00:46,  2.00s/trial, best=90.9788, objective=112.535][I 2026-03-28 07:53:29,921] Trial 7 finished with value: 88.01974774304456 and parameters: {'n_estimators': 251, 'learning_rate': 0.09767966657678313, 'num_leaves': 42, 'max_depth': -1, 'min_child_samples': 8, 'subsample': 0.6125716742746937, 'colsample_bytree': 0.8545641645055122, 'reg_alpha': 7.693711312648862e-05, 'reg_lambda': 0.0036307373939807324}. Best is trial 7 with value: 88.01974774304456.
lightgbm_regressor_study [validation_mse]:  27%|██▋       | 8/30 [00:21<01:23,  3.81s/trial, best=88.0197, objective=88.0197][I 2026-03-28 07:53:31,989] Trial 8 finished with value: 99.49187712699072 and parameters: {'n_estimators': 298, 'learning_rate': 0.021102634054601693, 'num_leaves': 35, 'max_depth': -1, 'min_child_samples': 38, 'subsample': 0.9232481518257668, 'colsample_bytree': 0.8533615026041694, 'reg_alpha': 0.16934155410667973, 'reg_lambda': 0.42238115972862367}. Best is trial 7 with value: 88.01974774304456.
lightgbm_regressor_study [validation_mse]:  30%|███       | 9/30 [00:23<01:08,  3.27s/trial, best=88.0197, objective=99.4919][I 2026-03-28 07:53:32,688] Trial 9 finished with value: 95.32310682264757 and parameters: {'n_estimators': 124, 'learning_rate': 0.1449592822362264, 'num_leaves': 41, 'max_depth': 4, 'min_child_samples': 20, 'subsample': 0.9272059063689972, 'colsample_bytree': 0.9442922333025374, 'reg_alpha': 1.1008110571039529e-06, 'reg_lambda': 0.0037603746651791235}. Best is trial 7 with value: 88.01974774304456.
lightgbm_regressor_study [validation_mse]:  33%|███▎      | 10/30 [00:24<00:49,  2.47s/trial, best=88.0197, objective=95.3231][I 2026-03-28 07:53:34,914] Trial 10 finished with value: 77.74917578638454 and parameters: {'n_estimators': 248, 'learning_rate': 0.07251078417216375, 'num_leaves': 15, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6154900799844731, 'colsample_bytree': 0.8189071324479794, 'reg_alpha': 5.424448089855673e-05, 'reg_lambda': 0.0012792037629618409}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  37%|███▋      | 11/30 [00:26<00:45,  2.40s/trial, best=77.7492, objective=77.7492][I 2026-03-28 07:53:37,111] Trial 11 finished with value: 79.75694645420724 and parameters: {'n_estimators': 253, 'learning_rate': 0.0724953006839564, 'num_leaves': 15, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.6123585862063115, 'colsample_bytree': 0.8167265665612354, 'reg_alpha': 8.156228133292757e-05, 'reg_lambda': 0.0014812306470516452}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  40%|████      | 12/30 [00:29<00:42,  2.34s/trial, best=77.7492, objective=79.7569][I 2026-03-28 07:53:40,474] Trial 12 finished with value: 81.34872033037367 and parameters: {'n_estimators': 251, 'learning_rate': 0.05818201122466691, 'num_leaves': 17, 'max_depth': 6, 'min_child_samples': 6, 'subsample': 0.6181470472279326, 'colsample_bytree': 0.7785059534749844, 'reg_alpha': 1.6235986754056797e-05, 'reg_lambda': 0.0002641974794904743}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  43%|████▎     | 13/30 [00:32<00:45,  2.65s/trial, best=77.7492, objective=81.3487][I 2026-03-28 07:53:43,602] Trial 13 finished with value: 81.5556957872941 and parameters: {'n_estimators': 251, 'learning_rate': 0.0703057891855127, 'num_leaves': 28, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.6898693025872835, 'colsample_bytree': 0.822196762065712, 'reg_alpha': 0.013470293908452332, 'reg_lambda': 0.00014799961639661222}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  47%|████▋     | 14/30 [00:35<00:44,  2.79s/trial, best=77.7492, objective=81.5557][I 2026-03-28 07:53:45,747] Trial 14 finished with value: 87.28530107709894 and parameters: {'n_estimators': 226, 'learning_rate': 0.029432988077951236, 'num_leaves': 16, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.662852268571221, 'colsample_bytree': 0.7941240784789847, 'reg_alpha': 0.003919671267229426, 'reg_lambda': 0.012172751468722069}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  50%|█████     | 15/30 [00:37<00:38,  2.60s/trial, best=77.7492, objective=87.2853][I 2026-03-28 07:53:49,758] Trial 15 finished with value: 82.88714442073709 and parameters: {'n_estimators': 282, 'learning_rate': 0.0897016428804375, 'num_leaves': 25, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.7667262189141304, 'colsample_bytree': 0.9917702367090977, 'reg_alpha': 4.1521650778884745e-05, 'reg_lambda': 6.932107024790756}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  53%|█████▎    | 16/30 [00:41<00:42,  3.02s/trial, best=77.7492, objective=82.8871][I 2026-03-28 07:53:50,915] Trial 16 finished with value: 107.00649507724796 and parameters: {'n_estimators': 81, 'learning_rate': 0.03487776753903612, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 13, 'subsample': 0.7686367262595106, 'colsample_bytree': 0.7238803118866866, 'reg_alpha': 7.706444240885211e-06, 'reg_lambda': 0.0006537693186977485}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  57%|█████▋    | 17/30 [00:42<00:32,  2.46s/trial, best=77.7492, objective=107.006][I 2026-03-28 07:53:53,384] Trial 17 finished with value: 83.48328261713206 and parameters: {'n_estimators': 271, 'learning_rate': 0.09897535004574542, 'num_leaves': 21, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.6519088939897547, 'colsample_bytree': 0.8818763588177452, 'reg_alpha': 0.00014349147540801735, 'reg_lambda': 1.6811067194681343e-05}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  60%|██████    | 18/30 [00:45<00:29,  2.46s/trial, best=77.7492, objective=83.4833][I 2026-03-28 07:53:57,137] Trial 18 finished with value: 94.01788627817872 and parameters: {'n_estimators': 320, 'learning_rate': 0.06526705346594824, 'num_leaves': 33, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.7482465962019709, 'colsample_bytree': 0.6755969945736038, 'reg_alpha': 0.0022196842004995683, 'reg_lambda': 0.017587345541477728}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  63%|██████▎   | 19/30 [00:49<00:31,  2.85s/trial, best=77.7492, objective=94.0179][I 2026-03-28 07:53:59,774] Trial 19 finished with value: 116.17119487875416 and parameters: {'n_estimators': 224, 'learning_rate': 0.01037397785714494, 'num_leaves': 15, 'max_depth': 6, 'min_child_samples': 26, 'subsample': 0.9911945230518526, 'colsample_bytree': 0.8261680991680495, 'reg_alpha': 0.00032279328654903205, 'reg_lambda': 0.0008608364416646424}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  67%|██████▋   | 20/30 [00:51<00:27,  2.79s/trial, best=77.7492, objective=116.171][I 2026-03-28 07:54:04,631] Trial 20 finished with value: 91.29151179521155 and parameters: {'n_estimators': 270, 'learning_rate': 0.041422838540882294, 'num_leaves': 63, 'max_depth': 6, 'min_child_samples': 5, 'subsample': 0.6494579087113869, 'colsample_bytree': 0.7721747594334724, 'reg_alpha': 3.406023483649652e-05, 'reg_lambda': 4.606826156979024e-05}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  70%|███████   | 21/30 [00:56<00:30,  3.41s/trial, best=77.7492, objective=91.2915][I 2026-03-28 07:54:07,115] Trial 21 finished with value: 78.1883271380851 and parameters: {'n_estimators': 246, 'learning_rate': 0.0576831845489063, 'num_leaves': 19, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6047088841752168, 'colsample_bytree': 0.7654672661325679, 'reg_alpha': 1.7117283353496342e-05, 'reg_lambda': 0.0005422269716690974}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  73%|███████▎  | 22/30 [00:59<00:25,  3.13s/trial, best=77.7492, objective=78.1883][I 2026-03-28 07:54:09,583] Trial 22 finished with value: 78.97796819741916 and parameters: {'n_estimators': 231, 'learning_rate': 0.051558543334893764, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.6132076270260169, 'colsample_bytree': 0.8196696859417657, 'reg_alpha': 2.5955000553926716e-06, 'reg_lambda': 0.0010215535018329555}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  77%|███████▋  | 23/30 [01:01<00:20,  2.93s/trial, best=77.7492, objective=78.978] [I 2026-03-28 07:54:11,868] Trial 23 finished with value: 79.47254507314648 and parameters: {'n_estimators': 227, 'learning_rate': 0.04946722261215531, 'num_leaves': 21, 'max_depth': 6, 'min_child_samples': 10, 'subsample': 0.6650463862691661, 'colsample_bytree': 0.7453072736676534, 'reg_alpha': 1.1782301568724085e-06, 'reg_lambda': 0.01382972018417788}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  80%|████████  | 24/30 [01:03<00:16,  2.74s/trial, best=77.7492, objective=79.4725][I 2026-03-28 07:54:14,100] Trial 24 finished with value: 84.42031969061036 and parameters: {'n_estimators': 205, 'learning_rate': 0.027475385898620218, 'num_leaves': 20, 'max_depth': 6, 'min_child_samples': 9, 'subsample': 0.6039460790455812, 'colsample_bytree': 0.6812914514322427, 'reg_alpha': 4.8207544145874475e-06, 'reg_lambda': 0.00031302909097032506}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  83%|████████▎ | 25/30 [01:06<00:12,  2.59s/trial, best=77.7492, objective=84.4203][I 2026-03-28 07:54:16,735] Trial 25 finished with value: 90.44393300058123 and parameters: {'n_estimators': 230, 'learning_rate': 0.08287185247464234, 'num_leaves': 26, 'max_depth': 8, 'min_child_samples': 15, 'subsample': 0.6381153374857736, 'colsample_bytree': 0.8690139025902076, 'reg_alpha': 1.1169660311923796e-05, 'reg_lambda': 1.2010582509801884e-06}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  87%|████████▋ | 26/30 [01:08<00:10,  2.60s/trial, best=77.7492, objective=90.4439][I 2026-03-28 07:54:18,807] Trial 26 finished with value: 83.5284562796369 and parameters: {'n_estimators': 193, 'learning_rate': 0.1178691597872029, 'num_leaves': 19, 'max_depth': 6, 'min_child_samples': 12, 'subsample': 0.7006883943522274, 'colsample_bytree': 0.9056257599849026, 'reg_alpha': 2.4750177906553955e-06, 'reg_lambda': 3.649815791749453e-05}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  90%|█████████ | 27/30 [01:10<00:07,  2.44s/trial, best=77.7492, objective=83.5285][I 2026-03-28 07:54:22,050] Trial 27 finished with value: 78.50986301626395 and parameters: {'n_estimators': 234, 'learning_rate': 0.03668822328620197, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.6836270431286031, 'colsample_bytree': 0.8335002039485865, 'reg_alpha': 1.86044102918215e-05, 'reg_lambda': 0.0036646140099590475}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  93%|█████████▎| 28/30 [01:13<00:05,  2.68s/trial, best=77.7492, objective=78.5099][I 2026-03-28 07:54:26,197] Trial 28 finished with value: 83.50384406299773 and parameters: {'n_estimators': 288, 'learning_rate': 0.036988384105565014, 'num_leaves': 31, 'max_depth': 6, 'min_child_samples': 7, 'subsample': 0.7307279513158804, 'colsample_bytree': 0.7629435126283074, 'reg_alpha': 1.953420847571119e-05, 'reg_lambda': 0.05033594296298553}. Best is trial 10 with value: 77.74917578638454.
lightgbm_regressor_study [validation_mse]:  97%|█████████▋| 29/30 [01:18<00:03,  3.12s/trial, best=77.7492, objective=83.5038][I 2026-03-28 07:54:27,653] Trial 29 finished with value: 106.67699367075194 and parameters: {'n_estimators': 161, 'learning_rate': 0.18505995430619274, 'num_leaves': 25, 'max_depth': 10, 'min_child_samples': 28, 'subsample': 0.6769781547282927, 'colsample_bytree': 0.6266361422537401, 'reg_alpha': 0.00024192203024696698, 'reg_lambda': 0.003715680084694488}. Best is trial 10 with value: 77.74917578638454.

lightgbm_regressor training complete.
Saved model bundle: C:\Users\eselerio\projects\pibre-model\results\lightgbm_regressor\model_20260328_075430.pkl
Saved metrics summary: C:\Users\eselerio\projects\pibre-model\results\lightgbm_regressor\metrics_20260328_075430.json
Saved Optuna summary: C:\Users\eselerio\projects\pibre-model\results\lightgbm_regressor\optuna_20260328_075430.json

,objective,n_estimators,learning_rate,num_leaves,max_depth,min_child_samples,subsample,colsample_bytree,reg_alpha,reg_lambda,random_state,verbosity,n_jobs
0,regression,248,0.072511,15,6,5,0.61549,0.818907,0.000054,0.001279,42,-1,-1

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.978836,23.835642,4.882176,1.387306,1.614905e+07,4.285164e+02,5.010541e+03,6.704907e+01,5.008219e+03
1,projected,0.957193,23.488439,4.846487,1.426559,1.794950e+07,8.796104e-12,4.191816e-11,1.486793e-12,4.183676e-11

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.817978,46.036138,6.784994,1.877650,2.045231e+07,4.314909e+02,4.948396e+03,7.068127e+01,4.928047e+03
1,projected,0.742585,45.331422,6.732861,1.892558,2.209351e+07,1.078107e-11,4.361939e-11,1.762211e-12,4.342837e-11

,target,raw_R2,raw_MSE,raw_RMSE,raw_MAE,raw_MAPE,projected_R2,projected_MSE,projected_RMSE,projected_MAE,projected_MAPE
0,Out_COD,0.996874,9.655023,3.107253,2.290791,7.045398e-03,0.998476,4.707713e+00,2.169727,1.502300,4.664767e-03
1,Out_TSS,0.996798,6.097619,2.469336,1.925459,8.790780e-03,0.998549,2.763015e+00,1.662232,1.234167,5.694004e-03
2,Out_TN,0.995842,0.445878,0.667741,0.475085,1.479172e-02,0.994560,5.833647e-01,0.763783,0.555596,1.658943e-02
3,Out_TP,0.998590,0.009790,0.098946,0.074890,1.314523e-02,0.947093,3.673570e-01,0.606100,0.228483,5.101327e-02
4,Out_S_S,0.803330,1.033093,1.016412,0.167435,2.596419e-02,0.606732,2.065808e+00,1.437292,0.837886,1.682313e-01
5,Out_S_I,0.999821,0.071704,0.267777,0.209710,4.520646e-03,1.000000,3.909695e-07,0.000625,0.000596,1.275079e-05
6,Out_S_NH4_N,0.860394,13.196241,3.632663,1.915520,2.519276e+06,0.850287,1.415153e+01,3.761851,2.252934,7.235794e+06
7,Out_S_NO3_N,0.838502,11.781977,3.432489,2.018998,1.259855e+01,0.828016,1.254695e+01,3.542167,2.216093,1.374569e+01
8,Out_S_PO4_P,0.998247,0.012756,0.112943,0.086919,1.183243e+06,0.950071,3.632253e-01,0.602682,0.223707,2.073742e+07
9,Out_S_O2,0.980349,0.036401,0.190792,0.132248,2.715077e-02,0.980349,3.640142e-02,0.190792,0.132248,2.715077e-02
10,Out_S_Alkalinity,0.859863,637.376528,25.246317,15.333183,2.889460e+08,0.860961,6.323794e+02,25.147154,15.198022,2.879008e+08
11,Out_X_I,0.998660,1.343561,1.159121,0.915544,9.650775e-03,0.999004,9.985094e-01,0.999254,0.762877,8.189608e-03
12,Out_X_S,-0.900947,1.887910,1.374013,0.157803,1.811758e+00,-1.611369,2.593461e+00,1.610422,0.776370,1.204678e+01
13,Out_X_H,0.995868,6.751300,2.598326,1.891721,1.182812e-02,0.996956,4.973735e+00,2.230187,1.584111,9.915030e-03
14,Out_X_AUT,0.847479,0.842289,0.917763,0.569442,1.413604e+07,0.739081,1.440917e+00,1.200382,0.882982,1.552861e+07

,count,mean,std,min,25%,50%,75%,max
raw_constraint_l2,2000.0,4.314909e+02,6.573461e+02,1.792173e+01,1.367381e+02,2.133979e+02,3.325016e+02,4.948396e+03
projected_constraint_l2,2000.0,1.078107e-11,6.907641e-12,1.960119e-13,5.558897e-12,9.158127e-12,1.467610e-11,4.361939e-11

[I 2026-03-28 07:54:31,504] A new study created in memory with name: catboost_regressor_study

=== Running catboost_regressor ===

catboost_regressor_study [validation_mse]:   0%|          | 0/30 [00:00<?, ?trial/s][I 2026-03-28 07:54:39,305] Trial 0 finished with value: 111.1175477452043 and parameters: {'iterations': 170, 'learning_rate': 0.17254716573280354, 'depth': 7, 'l2_leaf_reg': 0.9466503798478175, 'bagging_temperature': 0.7800932022121826, 'random_strength': 0.003775887545682684}. Best is trial 0 with value: 111.1175477452043.
catboost_regressor_study [validation_mse]:   3%|▎         | 1/30 [00:07<03:46,  7.80s/trial, best=111.118, objective=111.118][I 2026-03-28 07:54:43,713] Trial 1 finished with value: 122.17533407070768 and parameters: {'iterations': 93, 'learning_rate': 0.13394334706750485, 'depth': 7, 'l2_leaf_reg': 2.1745470981373622, 'bagging_temperature': 0.10292247147901223, 'random_strength': 3.8696122574142664}. Best is trial 0 with value: 111.1175477452043.
catboost_regressor_study [validation_mse]:   7%|▋         | 2/30 [00:12<02:42,  5.80s/trial, best=111.118, objective=122.175][I 2026-03-28 07:54:45,255] Trial 2 finished with value: 158.0726144285338 and parameters: {'iterations': 280, 'learning_rate': 0.018891200276189388, 'depth': 4, 'l2_leaf_reg': 0.040311020093778335, 'bagging_temperature': 1.5212112147976886, 'random_strength': 0.08730885649333642}. Best is trial 0 with value: 111.1175477452043.
catboost_regressor_study [validation_mse]:  10%|█         | 3/30 [00:13<01:44,  3.86s/trial, best=111.118, objective=158.073][I 2026-03-28 07:54:53,677] Trial 3 finished with value: 129.3796378608579 and parameters: {'iterations': 184, 'learning_rate': 0.023927528765580644, 'depth': 7, 'l2_leaf_reg': 0.028871770589042903, 'bagging_temperature': 1.4607232426760908, 'random_strength': 0.022654864504851786}. Best is trial 0 with value: 111.1175477452043.
catboost_regressor_study [validation_mse]:  13%|█▎        | 4/30 [00:22<02:27,  5.66s/trial, best=111.118, objective=129.38] [I 2026-03-28 07:54:54,629] Trial 4 finished with value: 111.03057087076041 and parameters: {'iterations': 189, 'learning_rate': 0.10508421338691762, 'depth': 4, 'l2_leaf_reg': 0.49831424930448204, 'bagging_temperature': 2.9620728443102124, 'random_strength': 0.0014853153980421612}. Best is trial 4 with value: 111.03057087076041.
catboost_regressor_study [validation_mse]:  17%|█▋        | 5/30 [00:23<01:39,  3.96s/trial, best=111.031, objective=111.031][I 2026-03-28 07:54:55,791] Trial 5 finished with value: 257.88445607552376 and parameters: {'iterations': 226, 'learning_rate': 0.016666983286066417, 'depth': 4, 'l2_leaf_reg': 13.561246837383383, 'bagging_temperature': 4.828160165372797, 'random_strength': 0.9777718780862645}. Best is trial 4 with value: 111.03057087076041.
catboost_regressor_study [validation_mse]:  20%|██        | 6/30 [00:24<01:12,  3.01s/trial, best=111.031, objective=257.884][I 2026-03-28 07:55:03,302] Trial 6 finished with value: 197.40981903452348 and parameters: {'iterations': 153, 'learning_rate': 0.013399060561509796, 'depth': 7, 'l2_leaf_reg': 0.28376353418686184, 'bagging_temperature': 0.6101911742238941, 'random_strength': 0.06786479434196534}. Best is trial 4 with value: 111.03057087076041.
catboost_regressor_study [validation_mse]:  23%|██▎       | 7/30 [00:31<01:43,  4.48s/trial, best=111.031, objective=197.41] [I 2026-03-28 07:55:04,167] Trial 7 finished with value: 104.32612101139428 and parameters: {'iterations': 88, 'learning_rate': 0.15242391728466367, 'depth': 5, 'l2_leaf_reg': 1.5381756551300383, 'bagging_temperature': 1.5585553804470549, 'random_strength': 0.08389112347840598}. Best is trial 7 with value: 104.32612101139428.
catboost_regressor_study [validation_mse]:  27%|██▋       | 8/30 [00:32<01:13,  3.33s/trial, best=104.326, objective=104.326][I 2026-03-28 07:55:22,257] Trial 8 finished with value: 242.1024268828346 and parameters: {'iterations': 211, 'learning_rate': 0.017398074711291726, 'depth': 8, 'l2_leaf_reg': 3.6202344812619107, 'bagging_temperature': 4.697494707820946, 'random_strength': 2.0414536703077757}. Best is trial 7 with value: 104.32612101139428.
catboost_regressor_study [validation_mse]:  30%|███       | 9/30 [00:50<02:46,  7.94s/trial, best=104.326, objective=242.102][I 2026-03-28 07:55:23,357] Trial 9 finished with value: 102.64597455216199 and parameters: {'iterations': 224, 'learning_rate': 0.15826541904647565, 'depth': 4, 'l2_leaf_reg': 0.04435527819593249, 'bagging_temperature': 0.22613644455269033, 'random_strength': 0.01597302366130558}. Best is trial 9 with value: 102.64597455216199.
catboost_regressor_study [validation_mse]:  33%|███▎      | 10/30 [00:51<01:56,  5.83s/trial, best=102.646, objective=102.646][I 2026-03-28 07:55:26,398] Trial 10 finished with value: 99.70960721589695 and parameters: {'iterations': 309, 'learning_rate': 0.05448786658934783, 'depth': 5, 'l2_leaf_reg': 0.01146285213283717, 'bagging_temperature': 3.1854602427698424, 'random_strength': 0.011768138993553334}. Best is trial 10 with value: 99.70960721589695.
catboost_regressor_study [validation_mse]:  37%|███▋      | 11/30 [00:54<01:34,  4.98s/trial, best=99.7096, objective=99.7096][I 2026-03-28 07:55:29,537] Trial 11 finished with value: 101.66821779083014 and parameters: {'iterations': 316, 'learning_rate': 0.06485618348127581, 'depth': 5, 'l2_leaf_reg': 0.010290597065996929, 'bagging_temperature': 3.3513080225253056, 'random_strength': 0.01003397957261834}. Best is trial 10 with value: 99.70960721589695.
catboost_regressor_study [validation_mse]:  40%|████      | 12/30 [00:58<01:19,  4.42s/trial, best=99.7096, objective=101.668][I 2026-03-28 07:55:32,558] Trial 12 finished with value: 101.7801522325809 and parameters: {'iterations': 314, 'learning_rate': 0.06113129725954219, 'depth': 5, 'l2_leaf_reg': 0.010841789039174939, 'bagging_temperature': 3.394671533165863, 'random_strength': 0.0063949016836783385}. Best is trial 10 with value: 99.70960721589695.
catboost_regressor_study [validation_mse]:  43%|████▎     | 13/30 [01:01<01:07,  3.99s/trial, best=99.7096, objective=101.78] [I 2026-03-28 07:55:35,629] Trial 13 finished with value: 101.86461070293717 and parameters: {'iterations': 312, 'learning_rate': 0.04580428796191275, 'depth': 5, 'l2_leaf_reg': 0.13834121782806166, 'bagging_temperature': 3.8583207162846915, 'random_strength': 0.31880835564181986}. Best is trial 10 with value: 99.70960721589695.
catboost_regressor_study [validation_mse]:  47%|████▋     | 14/30 [01:04<00:59,  3.72s/trial, best=99.7096, objective=101.865][I 2026-03-28 07:55:41,718] Trial 14 finished with value: 101.4414010840031 and parameters: {'iterations': 266, 'learning_rate': 0.0800445633264806, 'depth': 6, 'l2_leaf_reg': 0.010766774091986892, 'bagging_temperature': 2.3780636624041174, 'random_strength': 0.001045528813196251}. Best is trial 10 with value: 99.70960721589695.
catboost_regressor_study [validation_mse]:  50%|█████     | 15/30 [01:10<01:06,  4.43s/trial, best=99.7096, objective=101.441][I 2026-03-28 07:55:48,356] Trial 15 finished with value: 107.09435514603241 and parameters: {'iterations': 264, 'learning_rate': 0.03486835198204207, 'depth': 6, 'l2_leaf_reg': 0.09184628974205344, 'bagging_temperature': 2.479472404409533, 'random_strength': 0.0011946742296903882}. Best is trial 10 with value: 99.70960721589695.
catboost_regressor_study [validation_mse]:  53%|█████▎    | 16/30 [01:16<01:11,  5.10s/trial, best=99.7096, objective=107.094][I 2026-03-28 07:55:54,947] Trial 16 finished with value: 93.3538861959268 and parameters: {'iterations': 271, 'learning_rate': 0.08931557402412645, 'depth': 6, 'l2_leaf_reg': 0.027082374925989333, 'bagging_temperature': 2.2155322210033366, 'random_strength': 0.002628231346028667}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  57%|█████▋    | 17/30 [01:23<01:12,  5.55s/trial, best=93.3539, objective=93.3539][I 2026-03-28 07:56:01,491] Trial 17 finished with value: 112.91166747311834 and parameters: {'iterations': 285, 'learning_rate': 0.03772533999919673, 'depth': 6, 'l2_leaf_reg': 0.0244234993944635, 'bagging_temperature': 4.106641951167983, 'random_strength': 0.003502715295861911}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  60%|██████    | 18/30 [01:29<01:10,  5.85s/trial, best=93.3539, objective=112.912][I 2026-03-28 07:56:23,020] Trial 18 finished with value: 128.3107081091742 and parameters: {'iterations': 246, 'learning_rate': 0.09425056257924533, 'depth': 8, 'l2_leaf_reg': 0.08982524142911746, 'bagging_temperature': 1.828889346649553, 'random_strength': 0.03251595577817219}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  63%|██████▎   | 19/30 [01:51<01:56, 10.56s/trial, best=93.3539, objective=128.311][I 2026-03-28 07:56:26,078] Trial 19 finished with value: 100.04120159538648 and parameters: {'iterations': 291, 'learning_rate': 0.05365992126286376, 'depth': 5, 'l2_leaf_reg': 0.27383885922121554, 'bagging_temperature': 2.1774637389776985, 'random_strength': 0.0036884392735086558}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  67%|██████▋   | 20/30 [01:54<01:23,  8.30s/trial, best=93.3539, objective=100.041][I 2026-03-28 07:56:31,909] Trial 20 finished with value: 123.6892119462428 and parameters: {'iterations': 241, 'learning_rate': 0.027820627318372957, 'depth': 6, 'l2_leaf_reg': 0.021040439217161613, 'bagging_temperature': 2.9298411278450343, 'random_strength': 0.24069993160933525}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  70%|███████   | 21/30 [02:00<01:08,  7.56s/trial, best=93.3539, objective=123.689][I 2026-03-28 07:56:34,821] Trial 21 finished with value: 100.9496409941608 and parameters: {'iterations': 296, 'learning_rate': 0.05398122181101238, 'depth': 5, 'l2_leaf_reg': 0.21106246863022232, 'bagging_temperature': 2.370959683144353, 'random_strength': 0.002983110073543084}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  73%|███████▎  | 22/30 [02:03<00:49,  6.17s/trial, best=93.3539, objective=100.95] [I 2026-03-28 07:56:37,679] Trial 22 finished with value: 100.89577300432283 and parameters: {'iterations': 291, 'learning_rate': 0.07392954065066314, 'depth': 5, 'l2_leaf_reg': 0.07330298853019737, 'bagging_temperature': 2.8966046201522677, 'random_strength': 0.006367988824172422}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  77%|███████▋  | 23/30 [02:06<00:36,  5.17s/trial, best=93.3539, objective=100.896][I 2026-03-28 07:56:43,846] Trial 23 finished with value: 100.84253634138672 and parameters: {'iterations': 254, 'learning_rate': 0.04539442007783744, 'depth': 6, 'l2_leaf_reg': 0.5963336548275926, 'bagging_temperature': 1.897302810906769, 'random_strength': 0.0023996669364588744}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  80%|████████  | 24/30 [02:12<00:32,  5.47s/trial, best=93.3539, objective=100.843][I 2026-03-28 07:56:46,701] Trial 24 finished with value: 97.30551693666409 and parameters: {'iterations': 273, 'learning_rate': 0.11254823884044439, 'depth': 5, 'l2_leaf_reg': 0.018916496428774417, 'bagging_temperature': 2.085584390428057, 'random_strength': 0.011267817430058091}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  83%|████████▎ | 25/30 [02:15<00:23,  4.69s/trial, best=93.3539, objective=97.3055][I 2026-03-28 07:56:53,188] Trial 25 finished with value: 93.70953184609833 and parameters: {'iterations': 272, 'learning_rate': 0.10616737338218882, 'depth': 6, 'l2_leaf_reg': 0.018380263722867416, 'bagging_temperature': 1.1281403522610984, 'random_strength': 0.009988035718485687}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  87%|████████▋ | 26/30 [02:21<00:20,  5.23s/trial, best=93.3539, objective=93.7095][I 2026-03-28 07:56:59,362] Trial 26 finished with value: 93.94690134127534 and parameters: {'iterations': 271, 'learning_rate': 0.11743274911469258, 'depth': 6, 'l2_leaf_reg': 0.04403306794165115, 'bagging_temperature': 1.0780636136344057, 'random_strength': 0.03363453088401379}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  90%|█████████ | 27/30 [02:27<00:16,  5.51s/trial, best=93.3539, objective=93.9469][I 2026-03-28 07:57:10,676] Trial 27 finished with value: 106.27898939486248 and parameters: {'iterations': 234, 'learning_rate': 0.19046144808520038, 'depth': 7, 'l2_leaf_reg': 0.04674677317083249, 'bagging_temperature': 0.968281285226442, 'random_strength': 0.0410366317962921}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  93%|█████████▎| 28/30 [02:39<00:14,  7.25s/trial, best=93.3539, objective=106.279][I 2026-03-28 07:57:13,539] Trial 28 finished with value: 103.83262667785897 and parameters: {'iterations': 125, 'learning_rate': 0.08778528788639174, 'depth': 6, 'l2_leaf_reg': 0.06305616470363318, 'bagging_temperature': 1.2354029417585224, 'random_strength': 0.026256114352363736}. Best is trial 16 with value: 93.3538861959268.
catboost_regressor_study [validation_mse]:  97%|█████████▋| 29/30 [02:42<00:05,  5.94s/trial, best=93.3539, objective=103.833][I 2026-03-28 07:57:22,960] Trial 29 finished with value: 107.91668287716058 and parameters: {'iterations': 209, 'learning_rate': 0.11112981360471337, 'depth': 7, 'l2_leaf_reg': 0.14558813080140917, 'bagging_temperature': 0.6673777777126104, 'random_strength': 0.18990013245370296}. Best is trial 16 with value: 93.3538861959268.

catboost_regressor training complete.
Saved model bundle: C:\Users\eselerio\projects\pibre-model\results\catboost_regressor\model_20260328_075731.pkl
Saved metrics summary: C:\Users\eselerio\projects\pibre-model\results\catboost_regressor\metrics_20260328_075731.json
Saved Optuna summary: C:\Users\eselerio\projects\pibre-model\results\catboost_regressor\optuna_20260328_075731.json

,loss_function,iterations,learning_rate,depth,l2_leaf_reg,bootstrap_type,bagging_temperature,random_strength,random_seed,verbose,allow_writing_files
0,MultiRMSE,271,0.089316,6,0.027082,Bayesian,2.215532,0.002628,42,False,False

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.968029,31.080712,5.575008,1.845367,1.840634e+07,4.707906e+02,4.351991e+03,7.542279e+01,4.347502e+03
1,projected,0.955699,30.569260,5.528947,1.779485,1.998485e+07,6.644656e-12,3.467056e-11,1.181070e-12,3.456080e-11

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.546249,49.782028,7.055638,2.237903,2.184337e+07,4.740082e+02,4.040600e+03,7.858510e+01,4.030656e+03
1,projected,0.507272,48.908751,6.993479,2.139081,2.316116e+07,7.533482e-12,4.555710e-11,1.309209e-12,4.547474e-11

,target,raw_R2,raw_MSE,raw_RMSE,raw_MAE,raw_MAPE,projected_R2,projected_MSE,projected_RMSE,projected_MAE,projected_MAPE
0,Out_COD,0.994995,15.458608,3.931744,2.768819,8.654328e-03,0.996932,9.478187e+00,3.078666,2.002331,6.224486e-03
1,Out_TSS,0.994795,9.912218,3.148367,2.351385,1.075883e-02,0.996763,6.164664e+00,2.482874,1.853082,8.461088e-03
2,Out_TN,0.991529,0.908438,0.953120,0.723678,2.339388e-02,0.991457,9.161593e-01,0.957162,0.728330,2.356981e-02
3,Out_TP,0.993284,0.046632,0.215945,0.169398,2.945061e-02,0.946522,3.713262e-01,0.609365,0.239258,5.255004e-02
4,Out_S_S,0.238521,3.999996,1.999999,0.211606,3.056978e-02,0.214926,4.123942e+00,2.030749,0.440308,8.098389e-02
5,Out_S_I,0.995792,1.687972,1.299220,1.009536,2.268715e-02,1.000000,3.912836e-07,0.000626,0.000596,1.275112e-05
6,Out_S_NH4_N,0.848775,14.294515,3.780809,2.235421,3.934848e+06,0.844690,1.468065e+01,3.831534,2.393922,7.779329e+06
7,Out_S_NO3_N,0.831310,12.306638,3.508082,2.208809,1.352109e+01,0.819291,1.318354e+01,3.630914,2.438717,1.431899e+01
8,Out_S_PO4_P,0.993291,0.048803,0.220914,0.173322,4.276931e+06,0.950178,3.624443e-01,0.602033,0.222864,2.069645e+07
9,Out_S_O2,0.972106,0.051671,0.227312,0.159936,3.604367e-02,0.972106,5.167096e-02,0.227312,0.159936,3.604367e-02
10,Out_S_Alkalinity,0.854500,661.767554,25.724843,16.580266,3.051330e+08,0.855049,6.592688e+02,25.676229,16.494029,3.046708e+08
11,Out_X_I,0.995069,4.944433,2.223608,1.744273,1.992014e-02,0.997333,2.674605e+00,1.635422,1.239180,1.384632e-02
12,Out_X_S,-4.343896,5.307249,2.303747,0.169595,1.539190e+00,-4.794801,5.755061e+00,2.398971,0.708011,1.048291e+01
13,Out_X_H,0.990741,15.128241,3.889504,2.462481,1.525798e-02,0.990420,1.565160e+01,3.956210,2.510702,1.558023e-02
14,Out_X_AUT,0.842923,0.867454,0.931372,0.600025,1.430581e+07,0.828217,9.486655e-01,0.973995,0.654948,1.427077e+07

,count,mean,std,min,25%,50%,75%,max
raw_constraint_l2,2000.0,4.740082e+02,5.967720e+02,6.548432e+00,1.618295e+02,2.554990e+02,4.627263e+02,4.040600e+03
projected_constraint_l2,2000.0,7.533482e-12,4.554933e-12,1.136868e-13,4.174413e-12,6.691434e-12,9.691860e-12,4.555710e-11

[I 2026-03-28 07:57:32,240] A new study created in memory with name: adaboost_regressor_study

=== Running adaboost_regressor ===

adaboost_regressor_study [validation_mse]:   0%|          | 0/30 [00:00<?, ?trial/s][I 2026-03-28 07:57:36,137] Trial 0 finished with value: 163.21152705563884 and parameters: {'n_estimators': 125, 'learning_rate': 0.7969454818643931, 'loss': 'linear'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:   3%|▎         | 1/30 [00:03<01:52,  3.90s/trial, best=163.212, objective=163.212][I 2026-03-28 07:57:39,609] Trial 1 finished with value: 181.7246977803446 and parameters: {'n_estimators': 81, 'learning_rate': 0.01306673923805328, 'loss': 'linear'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:   7%|▋         | 2/30 [00:07<01:42,  3.65s/trial, best=163.212, objective=181.725][I 2026-03-28 07:57:41,441] Trial 2 finished with value: 170.60032165750872 and parameters: {'n_estimators': 54, 'learning_rate': 0.8706020878304853, 'loss': 'linear'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:  10%|█         | 3/30 [00:09<01:16,  2.82s/trial, best=163.212, objective=170.6]  [I 2026-03-28 07:57:44,903] Trial 3 finished with value: 168.67696808285564 and parameters: {'n_estimators': 86, 'learning_rate': 0.04059611610484305, 'loss': 'linear'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:  13%|█▎        | 4/30 [00:12<01:19,  3.07s/trial, best=163.212, objective=168.677][I 2026-03-28 07:57:51,688] Trial 4 finished with value: 169.50035266818696 and parameters: {'n_estimators': 172, 'learning_rate': 0.01901024531987036, 'loss': 'exponential'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:  17%|█▋        | 5/30 [00:19<01:50,  4.41s/trial, best=163.212, objective=169.5]  [I 2026-03-28 07:57:59,757] Trial 5 finished with value: 167.7325388404347 and parameters: {'n_estimators': 207, 'learning_rate': 0.025081156860452335, 'loss': 'square'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:  20%|██        | 6/30 [00:27<02:15,  5.66s/trial, best=163.212, objective=167.733][I 2026-03-28 07:58:06,683] Trial 6 finished with value: 165.36332802823625 and parameters: {'n_estimators': 172, 'learning_rate': 0.021930485556643693, 'loss': 'exponential'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:  23%|██▎       | 7/30 [00:34<02:19,  6.07s/trial, best=163.212, objective=165.363][I 2026-03-28 07:58:14,588] Trial 7 finished with value: 169.21666575678492 and parameters: {'n_estimators': 212, 'learning_rate': 0.040665633135147955, 'loss': 'square'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:  27%|██▋       | 8/30 [00:42<02:26,  6.65s/trial, best=163.212, objective=169.217][I 2026-03-28 07:58:17,493] Trial 8 finished with value: 170.28507093162435 and parameters: {'n_estimators': 74, 'learning_rate': 0.09780337016659407, 'loss': 'square'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:  30%|███       | 9/30 [00:45<01:55,  5.48s/trial, best=163.212, objective=170.285][I 2026-03-28 07:58:24,953] Trial 9 finished with value: 170.49864454775286 and parameters: {'n_estimators': 183, 'learning_rate': 0.0420167205437253, 'loss': 'square'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:  33%|███▎      | 10/30 [00:52<02:01,  6.09s/trial, best=163.212, objective=170.499][I 2026-03-28 07:58:29,581] Trial 10 finished with value: 164.87745319149766 and parameters: {'n_estimators': 125, 'learning_rate': 0.7340472227986772, 'loss': 'linear'}. Best is trial 0 with value: 163.21152705563884.
adaboost_regressor_study [validation_mse]:  37%|███▋      | 11/30 [00:57<01:47,  5.64s/trial, best=163.212, objective=164.877][I 2026-03-28 07:58:34,595] Trial 11 finished with value: 160.99111973811102 and parameters: {'n_estimators': 130, 'learning_rate': 0.9552896679671543, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  40%|████      | 12/30 [01:02<01:38,  5.45s/trial, best=160.991, objective=160.991][I 2026-03-28 07:58:40,562] Trial 12 finished with value: 163.99669291177491 and parameters: {'n_estimators': 132, 'learning_rate': 0.36131029556947863, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  43%|████▎     | 13/30 [01:08<01:35,  5.61s/trial, best=160.991, objective=163.997][I 2026-03-28 07:58:45,827] Trial 13 finished with value: 162.90410747238855 and parameters: {'n_estimators': 125, 'learning_rate': 0.33886235598190706, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  47%|████▋     | 14/30 [01:13<01:28,  5.50s/trial, best=160.991, objective=162.904][I 2026-03-28 07:58:49,555] Trial 14 finished with value: 164.07833783161965 and parameters: {'n_estimators': 107, 'learning_rate': 0.3039700946542548, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  50%|█████     | 15/30 [01:17<01:14,  4.97s/trial, best=160.991, objective=164.078][I 2026-03-28 07:58:56,795] Trial 15 finished with value: 166.2856594170434 and parameters: {'n_estimators': 238, 'learning_rate': 0.2997265580946327, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  53%|█████▎    | 16/30 [01:24<01:19,  5.65s/trial, best=160.991, objective=166.286][I 2026-03-28 07:59:02,431] Trial 16 finished with value: 164.15894413535955 and parameters: {'n_estimators': 149, 'learning_rate': 0.12707276506775467, 'loss': 'exponential'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  57%|█████▋    | 17/30 [01:30<01:13,  5.65s/trial, best=160.991, objective=164.159][I 2026-03-28 07:59:05,485] Trial 17 finished with value: 169.60952711364234 and parameters: {'n_estimators': 99, 'learning_rate': 0.46275136765418245, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  60%|██████    | 18/30 [01:33<00:58,  4.87s/trial, best=160.991, objective=169.61] [I 2026-03-28 07:59:10,634] Trial 18 finished with value: 165.65834979769463 and parameters: {'n_estimators': 148, 'learning_rate': 0.17906615200919845, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  63%|██████▎   | 19/30 [01:38<00:54,  4.95s/trial, best=160.991, objective=165.658][I 2026-03-28 07:59:14,626] Trial 19 finished with value: 169.08811081572668 and parameters: {'n_estimators': 118, 'learning_rate': 0.5060870529877813, 'loss': 'exponential'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  67%|██████▋   | 20/30 [01:42<00:46,  4.66s/trial, best=160.991, objective=169.088][I 2026-03-28 07:59:16,600] Trial 20 finished with value: 166.79933784839008 and parameters: {'n_estimators': 52, 'learning_rate': 0.17057928340516823, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  70%|███████   | 21/30 [01:44<00:34,  3.86s/trial, best=160.991, objective=166.799][I 2026-03-28 07:59:20,328] Trial 21 finished with value: 165.22775849954687 and parameters: {'n_estimators': 135, 'learning_rate': 0.9718916431083594, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  73%|███████▎  | 22/30 [01:48<00:30,  3.82s/trial, best=160.991, objective=165.228][I 2026-03-28 07:59:23,862] Trial 22 finished with value: 163.4589598383515 and parameters: {'n_estimators': 108, 'learning_rate': 0.5915560807545924, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  77%|███████▋  | 23/30 [01:51<00:26,  3.73s/trial, best=160.991, objective=163.459][I 2026-03-28 07:59:28,015] Trial 23 finished with value: 167.36569562165047 and parameters: {'n_estimators': 159, 'learning_rate': 0.993961600333998, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  80%|████████  | 24/30 [01:55<00:23,  3.86s/trial, best=160.991, objective=167.366][I 2026-03-28 07:59:32,488] Trial 24 finished with value: 166.92945777670215 and parameters: {'n_estimators': 142, 'learning_rate': 0.22392274989378344, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  83%|████████▎ | 25/30 [02:00<00:20,  4.04s/trial, best=160.991, objective=166.929][I 2026-03-28 07:59:36,017] Trial 25 finished with value: 166.9032470042222 and parameters: {'n_estimators': 119, 'learning_rate': 0.6324554595158338, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  87%|████████▋ | 26/30 [02:03<00:15,  3.89s/trial, best=160.991, objective=166.903][I 2026-03-28 07:59:39,306] Trial 26 finished with value: 168.31063455071762 and parameters: {'n_estimators': 102, 'learning_rate': 0.42521533253411137, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  90%|█████████ | 27/30 [02:07<00:11,  3.71s/trial, best=160.991, objective=168.311][I 2026-03-28 07:59:45,379] Trial 27 finished with value: 166.47052932819585 and parameters: {'n_estimators': 163, 'learning_rate': 0.0796460254370205, 'loss': 'linear'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  93%|█████████▎| 28/30 [02:13<00:08,  4.42s/trial, best=160.991, objective=166.471][I 2026-03-28 07:59:51,234] Trial 28 finished with value: 172.1037092539567 and parameters: {'n_estimators': 191, 'learning_rate': 0.6954087670763696, 'loss': 'exponential'}. Best is trial 11 with value: 160.99111973811102.
adaboost_regressor_study [validation_mse]:  97%|█████████▋| 29/30 [02:18<00:04,  4.85s/trial, best=160.991, objective=172.104][I 2026-03-28 07:59:54,009] Trial 29 finished with value: 168.84503621203427 and parameters: {'n_estimators': 81, 'learning_rate': 0.2537039233345431, 'loss': 'square'}. Best is trial 11 with value: 160.99111973811102.

adaboost_regressor training complete.
Saved model bundle: C:\Users\eselerio\projects\pibre-model\results\adaboost_regressor\model_20260328_080021.pkl
Saved metrics summary: C:\Users\eselerio\projects\pibre-model\results\adaboost_regressor\metrics_20260328_080021.json
Saved Optuna summary: C:\Users\eselerio\projects\pibre-model\results\adaboost_regressor\optuna_20260328_080021.json

   n_estimators  learning_rate    loss  random_state
0           130        0.95529  linear            42

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.832312,163.465924,12.785379,5.849061,5.406554e+07,1.054950e+03,5.444343e+03,1.949274e+02,5.351503e+03
1,projected,0.449960,149.826136,12.240349,5.536110,5.434606e+07,3.589981e-11,1.547136e-10,5.117232e-12,1.546141e-10

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.755658,172.429852,13.131255,5.979241,5.355600e+07,1.022324e+03,5.003242e+03,1.908355e+02,4.992194e+03
1,projected,-0.772027,158.343747,12.583471,5.682321,5.378465e+07,3.616356e-11,1.491716e-10,5.136710e-12,1.491571e-10

,target,raw_R2,raw_MSE,raw_RMSE,raw_MAE,raw_MAPE,projected_R2,projected_MSE,projected_RMSE,projected_MAE,projected_MAPE
0,Out_COD,0.950075,154.213385,12.418268,9.973192,3.100506e-02,0.980518,6.017953e+01,7.757547,6.193602,1.934459e-02
1,Out_TSS,0.952830,89.831194,9.477932,7.524222,3.453871e-02,0.979430,3.917319e+01,6.258849,4.942997,2.257294e-02
2,Out_TN,0.970737,3.138206,1.771498,1.426590,4.456296e-02,0.928629,7.653898e+00,2.766568,2.247216,7.796695e-02
3,Out_TP,0.983826,0.112301,0.335113,0.270429,4.502097e-02,0.945970,3.751529e-01,0.612497,0.302072,6.034688e-02
4,Out_S_S,0.798939,1.056159,1.027696,0.841569,1.885119e-01,-3.090498,2.148710e+01,4.635418,3.705791,7.706670e-01
5,Out_S_I,0.985259,5.912399,2.431543,2.101377,4.518614e-02,1.000000,3.631598e-07,0.000603,0.000582,1.238603e-05
6,Out_S_NH4_N,0.257908,70.145952,8.375318,7.656564,3.401357e+07,0.555065,4.205736e+01,6.485164,5.266635,2.496006e+07
7,Out_S_NO3_N,0.538262,33.685773,5.803945,4.600345,1.577750e+01,0.395592,4.409418e+01,6.640345,5.609254,1.638905e+01
8,Out_S_PO4_P,0.971742,0.205573,0.453401,0.377890,1.010615e+07,0.950241,3.619831e-01,0.601650,0.269934,2.063212e+07
9,Out_S_O2,0.860292,0.258798,0.508722,0.419084,8.592839e-02,0.860292,2.587980e-01,0.508722,0.419084,8.592839e-02
10,Out_S_Alkalinity,0.555925,2019.753418,44.941667,37.556888,7.370663e+08,0.563291,1.986251e+03,44.567371,37.138889,7.329252e+08
11,Out_X_I,0.960140,39.967806,6.322010,5.072098,5.610796e-02,0.978848,2.120925e+01,4.605350,3.640469,4.038823e-02
12,Out_X_S,0.106632,0.887241,0.941935,0.129724,1.698213e+00,-16.459387,1.733965e+01,4.164091,3.311461,5.378396e+01
13,Out_X_H,0.899160,164.756596,12.835755,10.459647,7.124967e-02,0.928013,1.176157e+02,10.845076,8.886137,5.948293e-02
14,Out_X_AUT,0.543142,2.522983,1.588390,1.278989,2.215399e+07,-2.096416,1.709985e+01,4.135196,3.300688,2.825228e+07

,count,mean,std,min,25%,50%,75%,max
raw_constraint_l2,2000.0,1.022324e+03,7.845124e+02,7.112665e+01,4.994652e+02,7.917612e+02,1.248862e+03,5.003242e+03
projected_constraint_l2,2000.0,3.616356e-11,2.614822e-11,5.217532e-13,1.525456e-11,3.097902e-11,5.094635e-11,1.491716e-10

[I 2026-03-28 08:00:21,607] A new study created in memory with name: random_forest_regressor_study

=== Running random_forest_regressor ===

random_forest_regressor_study [validation_mse]:   0%|          | 0/30 [00:00<?, ?trial/s][I 2026-03-28 08:00:21,947] Trial 0 finished with value: 248.77193815725047 and parameters: {'n_estimators': 212, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.8005575058716043}. Best is trial 0 with value: 248.77193815725047.
random_forest_regressor_study [validation_mse]:   3%|▎         | 1/30 [00:00<00:09,  2.97trial/s, best=248.772, objective=248.772][I 2026-03-28 08:00:22,347] Trial 1 finished with value: 270.1097059264328 and parameters: {'n_estimators': 313, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 0.762378215816119}. Best is trial 0 with value: 248.77193815725047.
random_forest_regressor_study [validation_mse]:   7%|▋         | 2/30 [00:00<00:10,  2.67trial/s, best=248.772, objective=270.11] [I 2026-03-28 08:00:22,644] Trial 2 finished with value: 272.36181181578905 and parameters: {'n_estimators': 230, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 0.5998368910791798}. Best is trial 0 with value: 248.77193815725047.
random_forest_regressor_study [validation_mse]:  10%|█         | 3/30 [00:01<00:09,  2.95trial/s, best=248.772, objective=272.362][I 2026-03-28 08:00:23,059] Trial 3 finished with value: 252.61854543276056 and parameters: {'n_estimators': 254, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.9041986740582306}. Best is trial 0 with value: 248.77193815725047.
random_forest_regressor_study [validation_mse]:  13%|█▎        | 4/30 [00:01<00:09,  2.71trial/s, best=248.772, objective=252.619][I 2026-03-28 08:00:23,373] Trial 4 finished with value: 272.1101230667468 and parameters: {'n_estimators': 191, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.6293899908000085}. Best is trial 0 with value: 248.77193815725047.
random_forest_regressor_study [validation_mse]:  17%|█▋        | 5/30 [00:01<00:08,  2.86trial/s, best=248.772, objective=272.11] [I 2026-03-28 08:00:23,791] Trial 5 finished with value: 246.8066512789707 and parameters: {'n_estimators': 299, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 0.9474136752138245}. Best is trial 5 with value: 246.8066512789707.
random_forest_regressor_study [validation_mse]:  20%|██        | 6/30 [00:02<00:08,  2.69trial/s, best=246.807, objective=246.807][I 2026-03-28 08:00:24,215] Trial 6 finished with value: 233.91193827210267 and parameters: {'n_estimators': 279, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.9143687545759647}. Best is trial 6 with value: 233.91193827210267.
random_forest_regressor_study [validation_mse]:  23%|██▎       | 7/30 [00:02<00:08,  2.57trial/s, best=233.912, objective=233.912][I 2026-03-28 08:00:24,574] Trial 7 finished with value: 254.64744249554334 and parameters: {'n_estimators': 207, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.5993578407670862}. Best is trial 6 with value: 233.91193827210267.
random_forest_regressor_study [validation_mse]:  27%|██▋       | 8/30 [00:02<00:08,  2.63trial/s, best=233.912, objective=254.647][I 2026-03-28 08:00:24,787] Trial 8 finished with value: 233.04599408800405 and parameters: {'n_estimators': 101, 'max_depth': None, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.9315517129377968}. Best is trial 8 with value: 233.04599408800405.
random_forest_regressor_study [validation_mse]:  30%|███       | 9/30 [00:03<00:06,  3.06trial/s, best=233.046, objective=233.046][I 2026-03-28 08:00:25,180] Trial 9 finished with value: 245.87267989193202 and parameters: {'n_estimators': 287, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.7361074625809747}. Best is trial 8 with value: 233.04599408800405.
random_forest_regressor_study [validation_mse]:  33%|███▎      | 10/30 [00:03<00:06,  2.88trial/s, best=233.046, objective=245.873][I 2026-03-28 08:00:25,366] Trial 10 finished with value: 231.20190265461076 and parameters: {'n_estimators': 106, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.9916538350655753}. Best is trial 10 with value: 231.20190265461076.
random_forest_regressor_study [validation_mse]:  37%|███▋      | 11/30 [00:03<00:05,  3.36trial/s, best=231.202, objective=231.202][I 2026-03-28 08:00:25,557] Trial 11 finished with value: 230.6883183020355 and parameters: {'n_estimators': 109, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.9988370081936333}. Best is trial 11 with value: 230.6883183020355.
random_forest_regressor_study [validation_mse]:  40%|████      | 12/30 [00:03<00:04,  3.76trial/s, best=230.688, objective=230.688][I 2026-03-28 08:00:25,740] Trial 12 finished with value: 231.7438588541458 and parameters: {'n_estimators': 104, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.9970016731178163}. Best is trial 11 with value: 230.6883183020355.
random_forest_regressor_study [validation_mse]:  43%|████▎     | 13/30 [00:04<00:04,  4.15trial/s, best=230.688, objective=231.744][I 2026-03-28 08:00:26,255] Trial 13 finished with value: 228.2895487220265 and parameters: {'n_estimators': 381, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.8299745005983146}. Best is trial 13 with value: 228.2895487220265.
random_forest_regressor_study [validation_mse]:  47%|████▋     | 14/30 [00:04<00:05,  3.09trial/s, best=228.29, objective=228.29]  [I 2026-03-28 08:00:26,766] Trial 14 finished with value: 230.45851535265544 and parameters: {'n_estimators': 378, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.8409658398287965}. Best is trial 13 with value: 228.2895487220265.
random_forest_regressor_study [validation_mse]:  50%|█████     | 15/30 [00:05<00:05,  2.63trial/s, best=228.29, objective=230.459][I 2026-03-28 08:00:27,293] Trial 15 finished with value: 236.66506469410794 and parameters: {'n_estimators': 398, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 0.8336228052393174}. Best is trial 13 with value: 228.2895487220265.
random_forest_regressor_study [validation_mse]:  53%|█████▎    | 16/30 [00:05<00:05,  2.36trial/s, best=228.29, objective=236.665][I 2026-03-28 08:00:27,835] Trial 16 finished with value: 240.44715816507934 and parameters: {'n_estimators': 400, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.700477984841022}. Best is trial 13 with value: 228.2895487220265.
random_forest_regressor_study [validation_mse]:  57%|█████▋    | 17/30 [00:06<00:05,  2.18trial/s, best=228.29, objective=240.447][I 2026-03-28 08:00:28,313] Trial 17 finished with value: 246.8084374409561 and parameters: {'n_estimators': 357, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.8435390673423349}. Best is trial 13 with value: 228.2895487220265.
random_forest_regressor_study [validation_mse]:  60%|██████    | 18/30 [00:06<00:05,  2.15trial/s, best=228.29, objective=246.808][I 2026-03-28 08:00:28,779] Trial 18 finished with value: 233.05299418339254 and parameters: {'n_estimators': 344, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.6666126328591067}. Best is trial 13 with value: 228.2895487220265.
random_forest_regressor_study [validation_mse]:  63%|██████▎   | 19/30 [00:07<00:05,  2.15trial/s, best=228.29, objective=233.053][I 2026-03-28 08:00:29,261] Trial 19 finished with value: 237.78242213303218 and parameters: {'n_estimators': 358, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.8561945274258235}. Best is trial 13 with value: 228.2895487220265.
random_forest_regressor_study [validation_mse]:  67%|██████▋   | 20/30 [00:07<00:04,  2.12trial/s, best=228.29, objective=237.782][I 2026-03-28 08:00:29,691] Trial 20 finished with value: 240.75542586102435 and parameters: {'n_estimators': 328, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 0.5023700598265448}. Best is trial 13 with value: 228.2895487220265.
random_forest_regressor_study [validation_mse]:  70%|███████   | 21/30 [00:08<00:04,  2.18trial/s, best=228.29, objective=240.755][I 2026-03-28 08:00:29,963] Trial 21 finished with value: 226.54013219607032 and parameters: {'n_estimators': 153, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.8754986180062628}. Best is trial 21 with value: 226.54013219607032.
random_forest_regressor_study [validation_mse]:  73%|███████▎  | 22/30 [00:08<00:03,  2.49trial/s, best=226.54, objective=226.54] [I 2026-03-28 08:00:30,206] Trial 22 finished with value: 225.62042067130656 and parameters: {'n_estimators': 158, 'max_depth': None, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.7883068723322629}. Best is trial 22 with value: 225.62042067130656.
random_forest_regressor_study [validation_mse]:  77%|███████▋  | 23/30 [00:08<00:02,  2.82trial/s, best=225.62, objective=225.62][I 2026-03-28 08:00:30,452] Trial 23 finished with value: 225.7235415276512 and parameters: {'n_estimators': 154, 'max_depth': None, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.7799846721380516}. Best is trial 22 with value: 225.62042067130656.
random_forest_regressor_study [validation_mse]:  80%|████████  | 24/30 [00:08<00:01,  3.11trial/s, best=225.62, objective=225.724][I 2026-03-28 08:00:30,703] Trial 24 finished with value: 223.371853640029 and parameters: {'n_estimators': 158, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.7752847229001597}. Best is trial 24 with value: 223.371853640029.
random_forest_regressor_study [validation_mse]:  83%|████████▎ | 25/30 [00:09<00:01,  3.33trial/s, best=223.372, objective=223.372][I 2026-03-28 08:00:30,962] Trial 25 finished with value: 222.6654339046632 and parameters: {'n_estimators': 148, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.7685155853362995}. Best is trial 25 with value: 222.6654339046632.
random_forest_regressor_study [validation_mse]:  87%|████████▋ | 26/30 [00:09<00:01,  3.46trial/s, best=222.665, objective=222.665][I 2026-03-28 08:00:31,204] Trial 26 finished with value: 232.4122105635644 and parameters: {'n_estimators': 152, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.7291657181557174}. Best is trial 25 with value: 222.6654339046632.
random_forest_regressor_study [validation_mse]:  90%|█████████ | 27/30 [00:09<00:00,  3.65trial/s, best=222.665, objective=232.412][I 2026-03-28 08:00:31,476] Trial 27 finished with value: 227.12129600267227 and parameters: {'n_estimators': 177, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.6951341099628338}. Best is trial 25 with value: 222.6654339046632.
random_forest_regressor_study [validation_mse]:  93%|█████████▎| 28/30 [00:09<00:00,  3.65trial/s, best=222.665, objective=227.121][I 2026-03-28 08:00:31,687] Trial 28 finished with value: 229.00498558918767 and parameters: {'n_estimators': 130, 'max_depth': 10, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.7965698420791614}. Best is trial 25 with value: 222.6654339046632.
random_forest_regressor_study [validation_mse]:  97%|█████████▋| 29/30 [00:10<00:00,  3.93trial/s, best=222.665, objective=229.005][I 2026-03-28 08:00:31,953] Trial 29 finished with value: 231.3394579686041 and parameters: {'n_estimators': 172, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.7878561121508726}. Best is trial 25 with value: 222.6654339046632.

random_forest_regressor training complete.
Saved model bundle: C:\Users\eselerio\projects\pibre-model\results\random_forest_regressor\model_20260328_080033.pkl
Saved metrics summary: C:\Users\eselerio\projects\pibre-model\results\random_forest_regressor\metrics_20260328_080033.json
Saved Optuna summary: C:\Users\eselerio\projects\pibre-model\results\random_forest_regressor\optuna_20260328_080033.json

,n_estimators,max_depth,min_samples_split,min_samples_leaf,max_features,bootstrap,random_state,n_jobs
0,148,None,2,1,0.768516,True,42,-1

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.964877,18.132703,4.258251,1.964070,1.102619e+07,6.604363e+02,5.211527e+03,1.139702e+02,5.193415e+03
1,projected,0.938187,15.422125,3.927101,1.755461,1.271769e+07,1.078329e-11,6.380625e-11,1.768066e-12,6.275513e-11

,prediction_type,R2,MSE,RMSE,MAE,MAPE,constraint_mean_l2,constraint_max_l2,constraint_mean_abs,constraint_max_abs
0,raw,0.636195,126.655440,11.254130,5.222280,2.910579e+07,1.233694e+03,4.948837e+03,2.347984e+02,4.917842e+03
1,projected,-0.225678,106.592109,10.324345,4.564086,3.017294e+07,2.572451e-11,1.346724e-10,3.800627e-12,1.346052e-10

,target,raw_R2,raw_MSE,raw_RMSE,raw_MAE,raw_MAPE,projected_R2,projected_MSE,projected_RMSE,projected_MAE,projected_MAPE
0,Out_COD,0.949140,157.100865,12.533988,9.360022,2.921300e-02,0.979022,6.479826e+01,8.049736,5.985810,1.870146e-02
1,Out_TSS,0.939671,114.892093,10.718773,8.065590,3.715307e-02,0.968598,5.980195e+01,7.733172,5.798459,2.667654e-02
2,Out_TN,0.948311,5.543199,2.354400,1.798340,5.413445e-02,0.946732,5.712490e+00,2.390082,1.831126,5.500166e-02
3,Out_TP,0.926201,0.512419,0.715835,0.576375,9.001000e-02,0.940325,4.143487e-01,0.643699,0.315675,6.295186e-02
4,Out_S_S,0.572540,2.245418,1.498472,0.486455,7.971498e-02,-0.456596,7.651400e+00,2.766116,1.978174,3.965693e-01
5,Out_S_I,0.871820,51.411452,7.170178,5.776031,1.325327e-01,1.000000,3.971861e-07,0.000630,0.000597,1.273756e-05
6,Out_S_NH4_N,0.793605,19.509421,4.416947,2.456414,2.122348e+06,0.721976,2.628012e+01,5.126414,3.765468,1.550754e+07
7,Out_S_NO3_N,0.792596,15.131005,3.889859,2.526263,1.479349e+01,0.627741,2.715790e+01,5.211324,4.068774,1.382189e+01
8,Out_S_PO4_P,0.925612,0.541158,0.735634,0.596387,1.042396e+07,0.950389,3.609084e-01,0.600756,0.259552,2.050100e+07
9,Out_S_O2,0.780919,0.405830,0.637048,0.501794,1.159092e-01,0.780919,4.058295e-01,0.637048,0.501794,1.159092e-01
10,Out_S_Alkalinity,0.724018,1255.228863,35.429209,27.116947,4.089792e+08,0.734195,1.208943e+03,34.769864,26.464421,4.000193e+08
11,Out_X_I,0.879304,121.024029,11.001092,8.506015,9.695187e-02,0.970830,2.924914e+01,5.408248,4.072296,4.409030e-02
12,Out_X_S,-2.154877,3.133242,1.770097,0.115077,6.147075e-01,-13.907568,1.480533e+01,3.847770,2.732733,4.318003e+01
13,Out_X_H,0.907321,151.422706,12.305393,9.471156,6.208962e-02,0.908030,1.502644e+02,12.258240,9.343214,6.139146e-02
14,Out_X_AUT,0.686750,1.729910,1.315260,0.981334,1.506136e+07,0.450235,3.036058e+00,1.742429,1.343197,1.656624e+07

,count,mean,std,min,25%,50%,75%,max
raw_constraint_l2,2000.0,1.233694e+03,7.965642e+02,1.221538e+02,6.370443e+02,1.050439e+03,1.624540e+03,4.948837e+03
projected_constraint_l2,2000.0,2.572451e-11,1.996846e-11,2.049519e-13,1.108346e-11,2.035927e-11,3.551750e-11,1.346724e-10

[I 2026-03-28 08:00:34,755] A new study created in memory with name: svr_regressor_study

=== Running svr_regressor ===

svr_regressor_study [validation_mse]:   0%|          | 0/30 [00:00<?, ?trial/s][I 2026-03-28 08:00:34,856] Trial 0 finished with value: 199.96580758854574 and parameters: {'C': 1.3292918943162166, 'epsilon': 0.711447600934342, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 0 with value: 199.96580758854574.
svr_regressor_study [validation_mse]:   3%|▎         | 1/30 [00:00<00:02, 10.21trial/s, best=199.966, objective=199.966][I 2026-03-28 08:00:37,686] Trial 1 finished with value: 233.67653870304363 and parameters: {'C': 6.358358856676251, 'epsilon': 0.13311216080736885, 'kernel': 'linear', 'gamma': 'scale', 'degree': 2}. Best is trial 0 with value: 199.96580758854574.
svr_regressor_study [validation_mse]:   7%|▋         | 2/30 [00:02<00:40,  1.46s/trial, best=199.966, objective=233.677][I 2026-03-28 08:00:38,042] Trial 2 finished with value: 242.44195231188078 and parameters: {'C': 0.8179499475211672, 'epsilon': 0.03752055855124281, 'kernel': 'poly', 'gamma': 'auto', 'degree': 3}. Best is trial 0 with value: 199.96580758854574.
svr_regressor_study [validation_mse]:  10%|█         | 3/30 [00:03<00:27,  1.00s/trial, best=199.966, objective=242.442][I 2026-03-28 08:00:38,310] Trial 3 finished with value: 691.3153843739991 and parameters: {'C': 2.334586407601624, 'epsilon': 0.22673986523780384, 'kernel': 'poly', 'gamma': 'auto', 'degree': 2}. Best is trial 0 with value: 199.96580758854574.
svr_regressor_study [validation_mse]:  13%|█▎        | 4/30 [00:03<00:18,  1.37trial/s, best=199.966, objective=691.315][I 2026-03-28 08:00:38,394] Trial 4 finished with value: 242.7778650175239 and parameters: {'C': 0.15673095467235415, 'epsilon': 0.7025166339242155, 'kernel': 'rbf', 'gamma': 'auto', 'degree': 3}. Best is trial 0 with value: 199.96580758854574.
svr_regressor_study [validation_mse]:  17%|█▋        | 5/30 [00:03<00:18,  1.37trial/s, best=199.966, objective=242.778][I 2026-03-28 08:00:38,972] Trial 5 finished with value: 238.5232218660275 and parameters: {'C': 0.2323350351539011, 'epsilon': 0.030586566669785254, 'kernel': 'linear', 'gamma': 'scale', 'degree': 3}. Best is trial 0 with value: 199.96580758854574.
svr_regressor_study [validation_mse]:  20%|██        | 6/30 [00:04<00:12,  1.91trial/s, best=199.966, objective=238.523][I 2026-03-28 08:00:39,707] Trial 6 finished with value: 100.91157833365143 and parameters: {'C': 4.366473592979633, 'epsilon': 0.0035856126103453977, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 6 with value: 100.91157833365143.
svr_regressor_study [validation_mse]:  23%|██▎       | 7/30 [00:04<00:13,  1.72trial/s, best=100.912, objective=100.912][I 2026-03-28 08:00:39,989] Trial 7 finished with value: 232.54755154688067 and parameters: {'C': 0.18427970406864538, 'epsilon': 0.0038721180321745824, 'kernel': 'poly', 'gamma': 'auto', 'degree': 3}. Best is trial 6 with value: 100.91157833365143.
svr_regressor_study [validation_mse]:  27%|██▋       | 8/30 [00:05<00:10,  2.01trial/s, best=100.912, objective=232.548][I 2026-03-28 08:00:40,992] Trial 8 finished with value: 238.69388427872352 and parameters: {'C': 0.6963114377829286, 'epsilon': 0.042470585622618684, 'kernel': 'linear', 'gamma': 'scale', 'degree': 2}. Best is trial 6 with value: 100.91157833365143.
svr_regressor_study [validation_mse]:  30%|███       | 9/30 [00:06<00:13,  1.56trial/s, best=100.912, objective=238.694][I 2026-03-28 08:00:41,129] Trial 9 finished with value: 568.9243950910799 and parameters: {'C': 0.10388823104027935, 'epsilon': 0.2795015916508335, 'kernel': 'poly', 'gamma': 'auto', 'degree': 2}. Best is trial 6 with value: 100.91157833365143.
svr_regressor_study [validation_mse]:  33%|███▎      | 10/30 [00:06<00:09,  2.02trial/s, best=100.912, objective=568.924][I 2026-03-28 08:00:41,927] Trial 10 finished with value: 109.79686652143725 and parameters: {'C': 67.9807401796753, 'epsilon': 0.0010422971466648478, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 6 with value: 100.91157833365143.
svr_regressor_study [validation_mse]:  37%|███▋      | 11/30 [00:07<00:11,  1.71trial/s, best=100.912, objective=109.797][I 2026-03-28 08:00:42,725] Trial 11 finished with value: 109.79500212390283 and parameters: {'C': 52.84384205738849, 'epsilon': 0.0011068107068023284, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 6 with value: 100.91157833365143.
svr_regressor_study [validation_mse]:  40%|████      | 12/30 [00:07<00:11,  1.55trial/s, best=100.912, objective=109.795][I 2026-03-28 08:00:43,450] Trial 12 finished with value: 109.71497201235812 and parameters: {'C': 21.3982406058402, 'epsilon': 0.002651326957041677, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 6 with value: 100.91157833365143.
svr_regressor_study [validation_mse]:  43%|████▎     | 13/30 [00:08<00:11,  1.49trial/s, best=100.912, objective=109.715][I 2026-03-28 08:00:44,124] Trial 13 finished with value: 109.8483649058988 and parameters: {'C': 16.108186816612978, 'epsilon': 0.006224411575207714, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 6 with value: 100.91157833365143.
svr_regressor_study [validation_mse]:  47%|████▋     | 14/30 [00:09<00:10,  1.49trial/s, best=100.912, objective=109.848][I 2026-03-28 08:00:44,795] Trial 14 finished with value: 109.45228286554159 and parameters: {'C': 11.232260649454368, 'epsilon': 0.005277446173745153, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 6 with value: 100.91157833365143.
svr_regressor_study [validation_mse]:  50%|█████     | 15/30 [00:10<00:10,  1.49trial/s, best=100.912, objective=109.452][I 2026-03-28 08:00:45,406] Trial 15 finished with value: 108.86566475113582 and parameters: {'C': 7.064894158092137, 'epsilon': 0.010165594010996546, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 6 with value: 100.91157833365143.
svr_regressor_study [validation_mse]:  53%|█████▎    | 16/30 [00:10<00:09,  1.53trial/s, best=100.912, objective=108.866][I 2026-03-28 08:00:45,935] Trial 16 finished with value: 100.83951327124508 and parameters: {'C': 4.274758717268213, 'epsilon': 0.014302121685578822, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 16 with value: 100.83951327124508.
svr_regressor_study [validation_mse]:  57%|█████▋    | 17/30 [00:11<00:08,  1.62trial/s, best=100.84, objective=100.84]  [I 2026-03-28 08:00:46,430] Trial 17 finished with value: 99.18103793532464 and parameters: {'C': 3.1926955139432955, 'epsilon': 0.015332547789925923, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 3}. Best is trial 17 with value: 99.18103793532464.
svr_regressor_study [validation_mse]:  60%|██████    | 18/30 [00:11<00:06,  1.72trial/s, best=99.181, objective=99.181][I 2026-03-28 08:00:46,892] Trial 18 finished with value: 102.67624525217623 and parameters: {'C': 2.298388107628459, 'epsilon': 0.015315059829475406, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 3}. Best is trial 17 with value: 99.18103793532464.
svr_regressor_study [validation_mse]:  63%|██████▎   | 19/30 [00:12<00:05,  1.84trial/s, best=99.181, objective=102.676][I 2026-03-28 08:00:47,131] Trial 19 finished with value: 141.33878377129818 and parameters: {'C': 0.4494885339207624, 'epsilon': 0.07744652567951066, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 3}. Best is trial 17 with value: 99.18103793532464.
svr_regressor_study [validation_mse]:  67%|██████▋   | 20/30 [00:12<00:04,  2.21trial/s, best=99.181, objective=141.339][I 2026-03-28 08:01:23,478] Trial 20 finished with value: 238.55999399194013 and parameters: {'C': 30.146229037409476, 'epsilon': 0.01685471228908818, 'kernel': 'linear', 'gamma': 'scale', 'degree': 3}. Best is trial 17 with value: 99.18103793532464.
svr_regressor_study [validation_mse]:  70%|███████   | 21/30 [00:48<01:40, 11.21s/trial, best=99.181, objective=238.56] [I 2026-03-28 08:01:24,297] Trial 21 finished with value: 101.13536214271393 and parameters: {'C': 4.450731766151316, 'epsilon': 0.0022293278290753545, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 17 with value: 99.18103793532464.
svr_regressor_study [validation_mse]:  73%|███████▎  | 22/30 [00:49<01:04,  8.10s/trial, best=99.181, objective=101.135][I 2026-03-28 08:01:24,848] Trial 22 finished with value: 99.12913142962424 and parameters: {'C': 3.297683573078274, 'epsilon': 0.010300998055288347, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 22 with value: 99.12913142962424.
svr_regressor_study [validation_mse]:  77%|███████▋  | 23/30 [00:50<00:40,  5.83s/trial, best=99.1291, objective=99.1291][I 2026-03-28 08:01:25,335] Trial 23 finished with value: 110.80728912536054 and parameters: {'C': 1.5628917350365372, 'epsilon': 0.010398109005227826, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 3}. Best is trial 22 with value: 99.12913142962424.
svr_regressor_study [validation_mse]:  80%|████████  | 24/30 [00:50<00:25,  4.23s/trial, best=99.1291, objective=110.807][I 2026-03-28 08:01:25,894] Trial 24 finished with value: 109.04116272493326 and parameters: {'C': 10.351772507618245, 'epsilon': 0.022216151755464503, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 3}. Best is trial 22 with value: 99.12913142962424.
svr_regressor_study [validation_mse]:  83%|████████▎ | 25/30 [00:51<00:15,  3.13s/trial, best=99.1291, objective=109.041][I 2026-03-28 08:01:26,252] Trial 25 finished with value: 100.9791551825877 and parameters: {'C': 3.757422578829408, 'epsilon': 0.06493452208646032, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 4}. Best is trial 22 with value: 99.12913142962424.
svr_regressor_study [validation_mse]:  87%|████████▋ | 26/30 [00:51<00:09,  2.30s/trial, best=99.1291, objective=100.979][I 2026-03-28 08:01:26,737] Trial 26 finished with value: 111.0328725765503 and parameters: {'C': 1.5494181154419149, 'epsilon': 0.009383018139915829, 'kernel': 'rbf', 'gamma': 'auto', 'degree': 4}. Best is trial 22 with value: 99.12913142962424.
svr_regressor_study [validation_mse]:  90%|█████████ | 27/30 [00:51<00:05,  1.75s/trial, best=99.1291, objective=111.033][I 2026-03-28 08:01:27,263] Trial 27 finished with value: 108.39883131147114 and parameters: {'C': 6.911575357097751, 'epsilon': 0.023033122751955612, 'kernel': 'rbf', 'gamma': 'scale', 'degree': 3}. Best is trial 22 with value: 99.12913142962424.
svr_regressor_study [validation_mse]:  93%|█████████▎| 28/30 [00:52<00:02,  1.39s/trial, best=99.1291, objective=108.399][I 2026-03-28 08:01:27,643] Trial 28 finished with value: 907.1763134787769 and parameters: {'C': 3.137269476801684, 'epsilon': 0.006935294828755471, 'kernel': 'poly', 'gamma': 'scale', 'degree': 4}. Best is trial 22 with value: 99.12913142962424.
svr_regressor_study [validation_mse]:  97%|█████████▋| 29/30 [00:52<00:01,  1.08s/trial, best=99.1291, objective=907.176][I 2026-03-28 08:01:28,699] Trial 29 finished with value: 238.51308836340786 and parameters: {'C': 0.9141121262874017, 'epsilon': 0.06856158324172239, 'kernel': 'linear', 'gamma': 'scale', 'degree': 4}. Best is trial 22 with value: 99.12913142962424.
Training svr_regressor:  20%|██        | 1/5 [00:00<00:00, 53.99stage/s, objective=fit, stage=fit]